/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DailyPayError } from "./dailypayerror.js";

/**
 * A conflict occurred with the current state of the resource
 */
export type ErrorConflictData = {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorConflictError>;
  httpMeta: models.HTTPMetadata;
};

/**
 * A conflict occurred with the current state of the resource
 */
export class ErrorConflict extends DailyPayError {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorConflictError>;

  /** The original data that was passed to this error instance. */
  data$: ErrorConflictData;

  constructor(
    err: ErrorConflictData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "ErrorConflict";
  }
}

/** @internal */
export const ErrorConflict$inboundSchema: z.ZodType<
  ErrorConflict,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(models.ErrorConflictError$inboundSchema),
  HttpMeta: models.HTTPMetadata$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "HttpMeta": "httpMeta",
    });

    return new ErrorConflict(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
