/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DailyPayError } from "./dailypayerror.js";

/**
 * Not authorized to perform this operation
 */
export type ErrorForbiddenData = {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorForbiddenError>;
  httpMeta: models.HTTPMetadata;
};

/**
 * Not authorized to perform this operation
 */
export class ErrorForbidden extends DailyPayError {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorForbiddenError>;

  /** The original data that was passed to this error instance. */
  data$: ErrorForbiddenData;

  constructor(
    err: ErrorForbiddenData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "ErrorForbidden";
  }
}

/** @internal */
export const ErrorForbidden$inboundSchema: z.ZodType<
  ErrorForbidden,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(models.ErrorForbiddenError$inboundSchema),
  HttpMeta: models.HTTPMetadata$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "HttpMeta": "httpMeta",
    });

    return new ErrorForbidden(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
