/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DailyPayError } from "./dailypayerror.js";

/**
 * Bad Request
 */
export type JobUpdateErrorData = {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorJobUpdateError>;
  httpMeta: models.HTTPMetadata;
};

/**
 * Bad Request
 */
export class JobUpdateError extends DailyPayError {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorJobUpdateError>;

  /** The original data that was passed to this error instance. */
  data$: JobUpdateErrorData;

  constructor(
    err: JobUpdateErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "JobUpdateError";
  }
}

/** @internal */
export const JobUpdateError$inboundSchema: z.ZodType<
  JobUpdateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(models.ErrorJobUpdateError$inboundSchema),
  HttpMeta: models.HTTPMetadata$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "HttpMeta": "httpMeta",
    });

    return new JobUpdateError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
