// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// AccountCreateError - The request contained an error
type AccountCreateError struct {
	// A list of errors that occurred.
	Errors   []components.ErrorAccountCreateError `json:"errors"`
	HTTPMeta components.HTTPMetadata              `json:"-"`
}

var _ error = &AccountCreateError{}

func (e *AccountCreateError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
