// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ErrorNotFound - Resource was not found
type ErrorNotFound struct {
	// A list of errors that occurred.
	Errors   []components.ErrorNotFoundError `json:"errors"`
	HTTPMeta components.HTTPMetadata         `json:"-"`
}

var _ error = &ErrorNotFound{}

func (e *ErrorNotFound) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
