// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// JobUpdateError - Bad Request
type JobUpdateError struct {
	// A list of errors that occurred.
	Errors   []components.ErrorJobUpdateError `json:"errors"`
	HTTPMeta components.HTTPMetadata          `json:"-"`
}

var _ error = &JobUpdateError{}

func (e *JobUpdateError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
