// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"mockserver/internal/logging"
	"mockserver/internal/tracking"
	"net/http"
)

// GeneratedHandlers returns all generated handlers.
func GeneratedHandlers(ctx context.Context, dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) []*GeneratedHandler {
	return []*GeneratedHandler{
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/accounts", pathGetRestAccounts(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/accounts/{account_id}", pathGetRestAccountsAccountID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/health", pathGetRestHealth(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/jobs", pathGetRestJobs(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/jobs/{job_id}", pathGetRestJobsJobID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/organizations", pathGetRestOrganizations(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/organizations/{organization_id}", pathGetRestOrganizationsOrganizationID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/paychecks", pathGetRestPaychecks(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/paychecks/{paycheck_id}", pathGetRestPaychecksPaycheckID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/people/{person_id}", pathGetRestPeoplePersonID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/transfers", pathGetRestTransfers(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/rest/transfers/{transfer_id}", pathGetRestTransfersTransferID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPatch, "/rest/jobs/{job_id}", pathPatchRestJobsJobID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPatch, "/rest/people/{person_id}", pathPatchRestPeoplePersonID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/cards/generic", pathPostCardsGeneric(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/rest/accounts", pathPostRestAccounts(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/rest/transfers", pathPostRestTransfers(dir, rt)),
	}
}
