// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetRestPaychecksPaycheckID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "readPaycheck[0]":
			dir.HandlerFunc("readPaycheck", testReadPaycheckReadPaycheck0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testReadPaycheckReadPaycheck0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, true, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaycheckData = &components.PaycheckData{
		Data: components.PaycheckResource{
			ID: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
			Attributes: components.PaycheckAttributes{
				Status:               components.PaycheckAttributesStatusProcessing,
				PayPeriodEndsAt:      types.MustTimeFromString("2023-03-15T04:00:00Z"),
				PayPeriodStartsAt:    types.MustTimeFromString("2023-03-15T04:00:00Z"),
				DepositExpectedAt:    types.MustTimeFromString("2023-03-15T04:00:00Z"),
				TotalDebited:         types.Int64(0),
				GrossEarnings:        0,
				EmployerWithholdings: types.Int64(0),
				NetEarnings:          types.Int64(0),
				Currency:             "USD",
			},
			Links: components.PaycheckLinks{
				Self: "https://api.dailypay.com/rest/paychecks/f4e2fd6c-b567-447c-a003-b7315b8d22d2",
			},
			Relationships: components.PaycheckRelationships{
				Person: components.PersonRelationship{
					Data: components.PersonIdentifier{
						ID: "3fa8f641-5717-4562-b3fc-2c963f66afa6",
					},
				},
				Job: components.JobRelationship{
					Data: components.JobIdentifier{
						ID: "e9d84b0d-92ba-43c9-93bf-7c993313fa6f",
					},
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
