/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { accountsList } from "../funcs/accountsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type AccountsListQueryData = operations.ListAccountsResponse;

export function prefetchAccountsList(
  queryClient: QueryClient,
  client$: SDKCore,
  request?: operations.ListAccountsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAccountsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildAccountsListQuery(
  client$: SDKCore,
  request?: operations.ListAccountsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<AccountsListQueryData>;
} {
  return {
    queryKey: queryKeyAccountsList({
      filterPersonId: request?.filterPersonId,
      filterAccountType: request?.filterAccountType,
      filterSubtype: request?.filterSubtype,
      filterBy: request?.filterBy,
    }),
    queryFn: async function accountsListQueryFn(
      ctx,
    ): Promise<AccountsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(accountsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAccountsList(
  parameters: {
    filterPersonId?: string | undefined;
    filterAccountType?: models.FilterAccountType | undefined;
    filterSubtype?: string | undefined;
    filterBy?: string | undefined;
  },
): QueryKey {
  return ["@dailypay/dailypay", "Accounts", "list", parameters];
}
