/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  AccountsReadQueryData,
  buildAccountsReadQuery,
  prefetchAccountsRead,
  queryKeyAccountsRead,
} from "./accountsRead.core.js";
export {
  type AccountsReadQueryData,
  buildAccountsReadQuery,
  prefetchAccountsRead,
  queryKeyAccountsRead,
};

export type AccountsReadQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorNotFound
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get an Account object
 *
 * @remarks
 * Returns details about an account. This object represents a person's bank accounts, debit and pay cards, and earnings balance accounts.
 */
export function useAccountsRead(
  request: operations.ReadAccountRequest,
  options?: QueryHookOptions<AccountsReadQueryData, AccountsReadQueryError>,
): UseQueryResult<AccountsReadQueryData, AccountsReadQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildAccountsReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get an Account object
 *
 * @remarks
 * Returns details about an account. This object represents a person's bank accounts, debit and pay cards, and earnings balance accounts.
 */
export function useAccountsReadSuspense(
  request: operations.ReadAccountRequest,
  options?: SuspenseQueryHookOptions<
    AccountsReadQueryData,
    AccountsReadQueryError
  >,
): UseSuspenseQueryResult<AccountsReadQueryData, AccountsReadQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildAccountsReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setAccountsReadData(
  client: QueryClient,
  queryKeyBase: [accountId: string],
  data: AccountsReadQueryData,
): AccountsReadQueryData | undefined {
  const key = queryKeyAccountsRead(...queryKeyBase);

  return client.setQueryData<AccountsReadQueryData>(key, data);
}

export function invalidateAccountsRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[accountId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Accounts", "read", ...queryKeyBase],
  });
}

export function invalidateAllAccountsRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Accounts", "read"],
  });
}
