/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { cardTokenizationCreate } from "../funcs/cardTokenizationCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CardTokenizationCreateMutationVariables = {
  request: operations.CreateGenericCardTokenRequest;
  options?: RequestOptions;
};

export type CardTokenizationCreateMutationData =
  operations.CreateGenericCardTokenResponse;

export type CardTokenizationCreateMutationError =
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Obtain a card token
 *
 * @remarks
 * Obtain a PCI DSS Compliant card token. This token must be used in order to add a card to a user’s DailyPay account.
 */
export function useCardTokenizationCreateMutation(
  options?: MutationHookOptions<
    CardTokenizationCreateMutationData,
    CardTokenizationCreateMutationError,
    CardTokenizationCreateMutationVariables
  >,
): UseMutationResult<
  CardTokenizationCreateMutationData,
  CardTokenizationCreateMutationError,
  CardTokenizationCreateMutationVariables
> {
  const client = useSDKContext();
  return useMutation({
    ...buildCardTokenizationCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyCardTokenizationCreate(): MutationKey {
  return ["@dailypay/dailypay", "Card Tokenization", "create"];
}

export function buildCardTokenizationCreateMutation(
  client$: SDKCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CardTokenizationCreateMutationVariables,
  ) => Promise<CardTokenizationCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyCardTokenizationCreate(),
    mutationFn: function cardTokenizationCreateMutationFn({
      request,
      options,
    }): Promise<CardTokenizationCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(cardTokenizationCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
