/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useSDKContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildHealthGetHealthQuery,
  HealthGetHealthQueryData,
  prefetchHealthGetHealth,
  queryKeyHealthGetHealth,
} from "./healthGetHealth.core.js";
export {
  buildHealthGetHealthQuery,
  type HealthGetHealthQueryData,
  prefetchHealthGetHealth,
  queryKeyHealthGetHealth,
};

export type HealthGetHealthQueryError =
  | errors.ErrorUnauthorized
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Verify the status of the API
 *
 * @remarks
 * Returns a 200 status code if the API is up and running.
 */
export function useHealthGetHealth(
  options?: QueryHookOptions<
    HealthGetHealthQueryData,
    HealthGetHealthQueryError
  >,
): UseQueryResult<HealthGetHealthQueryData, HealthGetHealthQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildHealthGetHealthQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Verify the status of the API
 *
 * @remarks
 * Returns a 200 status code if the API is up and running.
 */
export function useHealthGetHealthSuspense(
  options?: SuspenseQueryHookOptions<
    HealthGetHealthQueryData,
    HealthGetHealthQueryError
  >,
): UseSuspenseQueryResult<HealthGetHealthQueryData, HealthGetHealthQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildHealthGetHealthQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setHealthGetHealthData(
  client: QueryClient,
  data: HealthGetHealthQueryData,
): HealthGetHealthQueryData | undefined {
  const key = queryKeyHealthGetHealth();

  return client.setQueryData<HealthGetHealthQueryData>(key, data);
}

export function invalidateAllHealthGetHealth(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Health", "getHealth"],
  });
}
