/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildJobsReadQuery,
  JobsReadQueryData,
  prefetchJobsRead,
  queryKeyJobsRead,
} from "./jobsRead.core.js";
export {
  buildJobsReadQuery,
  type JobsReadQueryData,
  prefetchJobsRead,
  queryKeyJobsRead,
};

export type JobsReadQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorNotFound
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a job object
 *
 * @remarks
 * Returns details about a person's employment.
 */
export function useJobsRead(
  request: operations.ReadJobRequest,
  options?: QueryHookOptions<JobsReadQueryData, JobsReadQueryError>,
): UseQueryResult<JobsReadQueryData, JobsReadQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildJobsReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a job object
 *
 * @remarks
 * Returns details about a person's employment.
 */
export function useJobsReadSuspense(
  request: operations.ReadJobRequest,
  options?: SuspenseQueryHookOptions<JobsReadQueryData, JobsReadQueryError>,
): UseSuspenseQueryResult<JobsReadQueryData, JobsReadQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildJobsReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setJobsReadData(
  client: QueryClient,
  queryKeyBase: [jobId: string],
  data: JobsReadQueryData,
): JobsReadQueryData | undefined {
  const key = queryKeyJobsRead(...queryKeyBase);

  return client.setQueryData<JobsReadQueryData>(key, data);
}

export function invalidateJobsRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[jobId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Jobs", "read", ...queryKeyBase],
  });
}

export function invalidateAllJobsRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Jobs", "read"],
  });
}
