/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { jobsList } from "../funcs/jobsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type JobsListQueryData = operations.ListJobsResponse;

export function prefetchJobsList(
  queryClient: QueryClient,
  client$: SDKCore,
  request?: operations.ListJobsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildJobsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildJobsListQuery(
  client$: SDKCore,
  request?: operations.ListJobsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<JobsListQueryData>;
} {
  return {
    queryKey: queryKeyJobsList({
      filterExternalIdentifiersPrimaryIdentifier: request
        ?.filterExternalIdentifiersPrimaryIdentifier,
      filterExternalIdentifiersEmployeeId: request
        ?.filterExternalIdentifiersEmployeeId,
      filterExternalIdentifiersGroup: request?.filterExternalIdentifiersGroup,
      filterPersonId: request?.filterPersonId,
      filterOrganizationId: request?.filterOrganizationId,
      filterBy: request?.filterBy,
    }),
    queryFn: async function jobsListQueryFn(ctx): Promise<JobsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(jobsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyJobsList(
  parameters: {
    filterExternalIdentifiersPrimaryIdentifier?: string | undefined;
    filterExternalIdentifiersEmployeeId?: string | undefined;
    filterExternalIdentifiersGroup?: string | undefined;
    filterPersonId?: string | undefined;
    filterOrganizationId?: string | undefined;
    filterBy?: string | undefined;
  },
): QueryKey {
  return ["@dailypay/dailypay", "Jobs", "list", parameters];
}
