/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildJobsListQuery,
  JobsListQueryData,
  prefetchJobsList,
  queryKeyJobsList,
} from "./jobsList.core.js";
export {
  buildJobsListQuery,
  type JobsListQueryData,
  prefetchJobsList,
  queryKeyJobsList,
};

export type JobsListQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a list of job objects
 *
 * @remarks
 * Returns a collection of job objects. This object represents a person's employment details.
 */
export function useJobsList(
  request?: operations.ListJobsRequest | undefined,
  options?: QueryHookOptions<JobsListQueryData, JobsListQueryError>,
): UseQueryResult<JobsListQueryData, JobsListQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildJobsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a list of job objects
 *
 * @remarks
 * Returns a collection of job objects. This object represents a person's employment details.
 */
export function useJobsListSuspense(
  request?: operations.ListJobsRequest | undefined,
  options?: SuspenseQueryHookOptions<JobsListQueryData, JobsListQueryError>,
): UseSuspenseQueryResult<JobsListQueryData, JobsListQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildJobsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setJobsListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      filterExternalIdentifiersPrimaryIdentifier?: string | undefined;
      filterExternalIdentifiersEmployeeId?: string | undefined;
      filterExternalIdentifiersGroup?: string | undefined;
      filterPersonId?: string | undefined;
      filterOrganizationId?: string | undefined;
      filterBy?: string | undefined;
    },
  ],
  data: JobsListQueryData,
): JobsListQueryData | undefined {
  const key = queryKeyJobsList(...queryKeyBase);

  return client.setQueryData<JobsListQueryData>(key, data);
}

export function invalidateJobsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      filterExternalIdentifiersPrimaryIdentifier?: string | undefined;
      filterExternalIdentifiersEmployeeId?: string | undefined;
      filterExternalIdentifiersGroup?: string | undefined;
      filterPersonId?: string | undefined;
      filterOrganizationId?: string | undefined;
      filterBy?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Jobs", "list", ...queryKeyBase],
  });
}

export function invalidateAllJobsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Jobs", "list"],
  });
}
