/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { jobsUpdate } from "../funcs/jobsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type JobsUpdateMutationVariables = {
  request: operations.UpdateJobRequest;
  options?: RequestOptions;
};

export type JobsUpdateMutationData = operations.UpdateJobResponse;

export type JobsUpdateMutationError =
  | errors.JobUpdateError
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorNotFound
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Update paycheck settings or deactivate a job
 *
 * @remarks
 * Update this job to set where pay should be deposited for paychecks related to this job,  or deactivate on-demand pay for this job.
 * Returns the job object if the update succeeded. Returns an error if update parameters are invalid.
 */
export function useJobsUpdateMutation(
  options?: MutationHookOptions<
    JobsUpdateMutationData,
    JobsUpdateMutationError,
    JobsUpdateMutationVariables
  >,
): UseMutationResult<
  JobsUpdateMutationData,
  JobsUpdateMutationError,
  JobsUpdateMutationVariables
> {
  const client = useSDKContext();
  return useMutation({
    ...buildJobsUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyJobsUpdate(): MutationKey {
  return ["@dailypay/dailypay", "Jobs", "update"];
}

export function buildJobsUpdateMutation(
  client$: SDKCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: JobsUpdateMutationVariables,
  ) => Promise<JobsUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyJobsUpdate(),
    mutationFn: function jobsUpdateMutationFn({
      request,
      options,
    }): Promise<JobsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(jobsUpdate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
