/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { organizationsRead } from "../funcs/organizationsRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type OrganizationsReadQueryData = operations.ReadOrganizationResponse;

export function prefetchOrganizationsRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadOrganizationRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildOrganizationsReadQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildOrganizationsReadQuery(
  client$: SDKCore,
  request: operations.ReadOrganizationRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<OrganizationsReadQueryData>;
} {
  return {
    queryKey: queryKeyOrganizationsRead(request.organizationId),
    queryFn: async function organizationsReadQueryFn(
      ctx,
    ): Promise<OrganizationsReadQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(organizationsRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyOrganizationsRead(organizationId: string): QueryKey {
  return ["@dailypay/dailypay", "Organizations", "read", organizationId];
}
