/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { organizationsList } from "../funcs/organizationsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type OrganizationsListQueryData = operations.ListOrganizationsResponse;

export function prefetchOrganizationsList(
  queryClient: QueryClient,
  client$: SDKCore,
  request?: operations.ListOrganizationsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildOrganizationsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildOrganizationsListQuery(
  client$: SDKCore,
  request?: operations.ListOrganizationsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<OrganizationsListQueryData>;
} {
  return {
    queryKey: queryKeyOrganizationsList({ filterBy: request?.filterBy }),
    queryFn: async function organizationsListQueryFn(
      ctx,
    ): Promise<OrganizationsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(organizationsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyOrganizationsList(
  parameters: { filterBy?: string | undefined },
): QueryKey {
  return ["@dailypay/dailypay", "Organizations", "list", parameters];
}
