/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { paychecksRead } from "../funcs/paychecksRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type PaychecksReadQueryData = operations.ReadPaycheckResponse;

export function prefetchPaychecksRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadPaycheckRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPaychecksReadQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildPaychecksReadQuery(
  client$: SDKCore,
  request: operations.ReadPaycheckRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<PaychecksReadQueryData>;
} {
  return {
    queryKey: queryKeyPaychecksRead(request.paycheckId),
    queryFn: async function paychecksReadQueryFn(
      ctx,
    ): Promise<PaychecksReadQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(paychecksRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPaychecksRead(paycheckId: string): QueryKey {
  return ["@dailypay/dailypay", "Paychecks", "read", paycheckId];
}
