/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPaychecksReadQuery,
  PaychecksReadQueryData,
  prefetchPaychecksRead,
  queryKeyPaychecksRead,
} from "./paychecksRead.core.js";
export {
  buildPaychecksReadQuery,
  type PaychecksReadQueryData,
  prefetchPaychecksRead,
  queryKeyPaychecksRead,
};

export type PaychecksReadQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorNotFound
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a Paycheck object
 *
 * @remarks
 * Returns details about a paycheck object.
 */
export function usePaychecksRead(
  request: operations.ReadPaycheckRequest,
  options?: QueryHookOptions<PaychecksReadQueryData, PaychecksReadQueryError>,
): UseQueryResult<PaychecksReadQueryData, PaychecksReadQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildPaychecksReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a Paycheck object
 *
 * @remarks
 * Returns details about a paycheck object.
 */
export function usePaychecksReadSuspense(
  request: operations.ReadPaycheckRequest,
  options?: SuspenseQueryHookOptions<
    PaychecksReadQueryData,
    PaychecksReadQueryError
  >,
): UseSuspenseQueryResult<PaychecksReadQueryData, PaychecksReadQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildPaychecksReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPaychecksReadData(
  client: QueryClient,
  queryKeyBase: [paycheckId: string],
  data: PaychecksReadQueryData,
): PaychecksReadQueryData | undefined {
  const key = queryKeyPaychecksRead(...queryKeyBase);

  return client.setQueryData<PaychecksReadQueryData>(key, data);
}

export function invalidatePaychecksRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[paycheckId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "read", ...queryKeyBase],
  });
}

export function invalidateAllPaychecksRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "read"],
  });
}
