/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPeopleReadQuery,
  PeopleReadQueryData,
  prefetchPeopleRead,
  queryKeyPeopleRead,
} from "./peopleRead.core.js";
export {
  buildPeopleReadQuery,
  type PeopleReadQueryData,
  prefetchPeopleRead,
  queryKeyPeopleRead,
};

export type PeopleReadQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorNotFound
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a person object
 *
 * @remarks
 * Returns details about a person.
 */
export function usePeopleRead(
  request: operations.ReadPersonRequest,
  options?: QueryHookOptions<PeopleReadQueryData, PeopleReadQueryError>,
): UseQueryResult<PeopleReadQueryData, PeopleReadQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildPeopleReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a person object
 *
 * @remarks
 * Returns details about a person.
 */
export function usePeopleReadSuspense(
  request: operations.ReadPersonRequest,
  options?: SuspenseQueryHookOptions<PeopleReadQueryData, PeopleReadQueryError>,
): UseSuspenseQueryResult<PeopleReadQueryData, PeopleReadQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildPeopleReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPeopleReadData(
  client: QueryClient,
  queryKeyBase: [personId: string],
  data: PeopleReadQueryData,
): PeopleReadQueryData | undefined {
  const key = queryKeyPeopleRead(...queryKeyBase);

  return client.setQueryData<PeopleReadQueryData>(key, data);
}

export function invalidatePeopleRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[personId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "People", "read", ...queryKeyBase],
  });
}

export function invalidateAllPeopleRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "People", "read"],
  });
}
