/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { peopleRead } from "../funcs/peopleRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type PeopleReadQueryData = operations.ReadPersonResponse;

export function prefetchPeopleRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadPersonRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPeopleReadQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildPeopleReadQuery(
  client$: SDKCore,
  request: operations.ReadPersonRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<PeopleReadQueryData>;
} {
  return {
    queryKey: queryKeyPeopleRead(request.personId),
    queryFn: async function peopleReadQueryFn(
      ctx,
    ): Promise<PeopleReadQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(peopleRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPeopleRead(personId: string): QueryKey {
  return ["@dailypay/dailypay", "People", "read", personId];
}
