/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { transfersList } from "../funcs/transfersList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type TransfersListQueryData = operations.ListTransfersResponse;

export function prefetchTransfersList(
  queryClient: QueryClient,
  client$: SDKCore,
  request?: operations.ListTransfersRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildTransfersListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildTransfersListQuery(
  client$: SDKCore,
  request?: operations.ListTransfersRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<TransfersListQueryData>;
} {
  return {
    queryKey: queryKeyTransfersList({
      include: request?.include,
      filterSubmittedAtGt: request?.filterSubmittedAtGt,
      filterBy: request?.filterBy,
    }),
    queryFn: async function transfersListQueryFn(
      ctx,
    ): Promise<TransfersListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(transfersList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyTransfersList(
  parameters: {
    include?: string | undefined;
    filterSubmittedAtGt?: Date | undefined;
    filterBy?: string | undefined;
  },
): QueryKey {
  return ["@dailypay/dailypay", "Transfers", "list", parameters];
}
