/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { transfersCreate } from "../funcs/transfersCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TransfersCreateMutationVariables = {
  request: operations.CreateTransferRequest;
  options?: RequestOptions;
};

export type TransfersCreateMutationData = operations.CreateTransferResponse;

export type TransfersCreateMutationError =
  | errors.TransferCreateError
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorConflict
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Request a transfer
 *
 * @remarks
 * Request transfer of funds from an `EARNINGS_BALANCE` account to a
 * personal `DEPOSITORY` or `CARD` account.
 */
export function useTransfersCreateMutation(
  options?: MutationHookOptions<
    TransfersCreateMutationData,
    TransfersCreateMutationError,
    TransfersCreateMutationVariables
  >,
): UseMutationResult<
  TransfersCreateMutationData,
  TransfersCreateMutationError,
  TransfersCreateMutationVariables
> {
  const client = useSDKContext();
  return useMutation({
    ...buildTransfersCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyTransfersCreate(): MutationKey {
  return ["@dailypay/dailypay", "Transfers", "create"];
}

export function buildTransfersCreateMutation(
  client$: SDKCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TransfersCreateMutationVariables,
  ) => Promise<TransfersCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyTransfersCreate(),
    mutationFn: function transfersCreateMutationFn({
      request,
      options,
    }): Promise<TransfersCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(transfersCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
