/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { transfersRead } from "../funcs/transfersRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type TransfersReadQueryData = operations.ReadTransferResponse;

export function prefetchTransfersRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadTransferRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildTransfersReadQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildTransfersReadQuery(
  client$: SDKCore,
  request: operations.ReadTransferRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<TransfersReadQueryData>;
} {
  return {
    queryKey: queryKeyTransfersRead(request.transferId, {
      include: request.include,
    }),
    queryFn: async function transfersReadQueryFn(
      ctx,
    ): Promise<TransfersReadQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(transfersRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyTransfersRead(
  transferId: string,
  parameters: { include?: string | undefined },
): QueryKey {
  return ["@dailypay/dailypay", "Transfers", "read", transferId, parameters];
}
