/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { DailyPayError } from "../models/errors/dailypayerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransfersListQuery,
  prefetchTransfersList,
  queryKeyTransfersList,
  TransfersListQueryData,
} from "./transfersList.core.js";
export {
  buildTransfersListQuery,
  prefetchTransfersList,
  queryKeyTransfersList,
  type TransfersListQueryData,
};

export type TransfersListQueryError =
  | errors.ErrorBadRequest
  | errors.ErrorUnauthorized
  | errors.ErrorForbidden
  | errors.ErrorUnexpected
  | DailyPayError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a list of transfers
 *
 * @remarks
 * Returns a list of transfer objects.
 */
export function useTransfersList(
  request?: operations.ListTransfersRequest | undefined,
  options?: QueryHookOptions<TransfersListQueryData, TransfersListQueryError>,
): UseQueryResult<TransfersListQueryData, TransfersListQueryError> {
  const client = useSDKContext();
  return useQuery({
    ...buildTransfersListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a list of transfers
 *
 * @remarks
 * Returns a list of transfer objects.
 */
export function useTransfersListSuspense(
  request?: operations.ListTransfersRequest | undefined,
  options?: SuspenseQueryHookOptions<
    TransfersListQueryData,
    TransfersListQueryError
  >,
): UseSuspenseQueryResult<TransfersListQueryData, TransfersListQueryError> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildTransfersListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransfersListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      include?: string | undefined;
      filterSubmittedAtGt?: Date | undefined;
      filterBy?: string | undefined;
    },
  ],
  data: TransfersListQueryData,
): TransfersListQueryData | undefined {
  const key = queryKeyTransfersList(...queryKeyBase);

  return client.setQueryData<TransfersListQueryData>(key, data);
}

export function invalidateTransfersList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      include?: string | undefined;
      filterSubmittedAtGt?: Date | undefined;
      filterBy?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Transfers", "list", ...queryKeyBase],
  });
}

export function invalidateAllTransfersList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Transfers", "list"],
  });
}
