/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it } from "vitest";

it.skip("Authentication Request Token", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step requestToken.test referencing operation requestToken not found in document`]",
  );
});
