/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cardTokenizationCreate } from "../funcs/cardTokenizationCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CardTokenization extends ClientSDK {
  /**
   * Obtain a card token
   *
   * @remarks
   * Obtain a PCI DSS Compliant card token. This token must be used in order to add a card to a user’s DailyPay account.
   */
  async create(
    request: operations.CreateGenericCardTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateGenericCardTokenResponse> {
    return unwrapAsync(cardTokenizationCreate(
      this,
      request,
      options,
    ));
  }
}
