/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Accounts } from "./accounts.js";
import { CardTokenization } from "./cardtokenization.js";
import { Health } from "./health.js";
import { Jobs } from "./jobs.js";
import { Organizations } from "./organizations.js";
import { Paychecks } from "./paychecks.js";
import { People } from "./people.js";
import { Transfers } from "./transfers.js";

export class SDK extends ClientSDK {
  private _jobs?: Jobs;
  get jobs(): Jobs {
    return (this._jobs ??= new Jobs(this._options));
  }

  private _accounts?: Accounts;
  get accounts(): Accounts {
    return (this._accounts ??= new Accounts(this._options));
  }

  private _transfers?: Transfers;
  get transfers(): Transfers {
    return (this._transfers ??= new Transfers(this._options));
  }

  private _paychecks?: Paychecks;
  get paychecks(): Paychecks {
    return (this._paychecks ??= new Paychecks(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _people?: People;
  get people(): People {
    return (this._people ??= new People(this._options));
  }

  private _cardTokenization?: CardTokenization;
  get cardTokenization(): CardTokenization {
    return (this._cardTokenization ??= new CardTokenization(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }
}
