// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetHealthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a healthcheck document
	Health200 *components.Health200
}

func (o *GetHealthResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHealthResponse) GetHealth200() *components.Health200 {
	if o == nil {
		return nil
	}
	return o.Health200
}
