// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ReadPaycheckGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadPaycheckGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadPaycheckGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ReadPaycheckGlobals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type ReadPaycheckRequest struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
	// Unique ID of the paycheck
	PaycheckID string `pathParam:"style=simple,explode=false,name=paycheck_id"`
}

func (r ReadPaycheckRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadPaycheckRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"paycheck_id"}); err != nil {
		return err
	}
	return nil
}

func (o *ReadPaycheckRequest) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *ReadPaycheckRequest) GetPaycheckID() string {
	if o == nil {
		return ""
	}
	return o.PaycheckID
}

type ReadPaycheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the paycheck object.
	PaycheckData *components.PaycheckData
}

func (o *ReadPaycheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadPaycheckResponse) GetPaycheckData() *components.PaycheckData {
	if o == nil {
		return nil
	}
	return o.PaycheckData
}
