// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ReadPersonGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadPersonGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadPersonGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ReadPersonGlobals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type ReadPersonRequest struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
	// Unique ID of the person
	PersonID string `pathParam:"style=simple,explode=false,name=person_id"`
}

func (r ReadPersonRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadPersonRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"person_id"}); err != nil {
		return err
	}
	return nil
}

func (o *ReadPersonRequest) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *ReadPersonRequest) GetPersonID() string {
	if o == nil {
		return ""
	}
	return o.PersonID
}

type ReadPersonResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the person object.
	PersonData *components.PersonData
}

func (o *ReadPersonResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadPersonResponse) GetPersonData() *components.PersonData {
	if o == nil {
		return nil
	}
	return o.PersonData
}
