// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ReadAccountGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (r ReadAccountGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadAccountGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ReadAccountGlobals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type ReadAccountRequest struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
	// Unique UUID of the Account.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
}

func (r ReadAccountRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadAccountRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"account_id"}); err != nil {
		return err
	}
	return nil
}

func (o *ReadAccountRequest) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *ReadAccountRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type ReadAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the account object.
	AccountData *components.AccountData
}

func (o *ReadAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadAccountResponse) GetAccountData() *components.AccountData {
	if o == nil {
		return nil
	}
	return o.AccountData
}
