// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UpdatePersonGlobals struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
}

func (u UpdatePersonGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePersonGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *UpdatePersonGlobals) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type UpdatePersonRequest struct {
	// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
	//
	Version *int64 `default:"3" header:"style=simple,explode=false,name=DailyPay-API-Version"`
	// Unique ID of the person
	PersonID string                      `pathParam:"style=simple,explode=false,name=person_id"`
	Body     components.PersonUpdateData `request:"mediaType=application/vnd.api+json"`
}

func (u UpdatePersonRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePersonRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"person_id", "body"}); err != nil {
		return err
	}
	return nil
}

func (o *UpdatePersonRequest) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *UpdatePersonRequest) GetPersonID() string {
	if o == nil {
		return ""
	}
	return o.PersonID
}

func (o *UpdatePersonRequest) GetBody() components.PersonUpdateData {
	if o == nil {
		return components.PersonUpdateData{}
	}
	return o.Body
}

type UpdatePersonResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the person object.
	PersonData *components.PersonData
}

func (o *UpdatePersonResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePersonResponse) GetPersonData() *components.PersonData {
	if o == nil {
		return nil
	}
	return o.PersonData
}
