/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPaychecksGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ListPaychecksRequest = {
  /**
   * Limit the results to documents related to a specific job
   */
  filterJobId?: string | undefined;
  /**
   * Limit the results to paychecks with the specified status
   */
  filterStatus?: models.FilterPaycheckStatus | undefined;
  /**
   * Limit the results to paychecks with deposit_expected_at greater than or equal to the specified date
   */
  filterDepositExpectedAtGte?: Date | undefined;
  /**
   * Limit the results to paychecks with deposit_expected_at less than the specified date
   */
  filterDepositExpectedAtLt?: Date | undefined;
  /**
   * Limit the results to paychecks with pay_period_ends_at greater than or equal to the specified date
   */
  filterPayPeriodEndsAtGte?: Date | undefined;
  /**
   * Limit the results to paychecks with pay_period_ends_at less than the specified date
   */
  filterPayPeriodEndsAtLt?: Date | undefined;
  /**
   * Limit the results to paychecks with pay_period_starts_at greater than or equal to the specified date
   */
  filterPayPeriodStartsAtGte?: Date | undefined;
  /**
   * Limit the results to paychecks with pay_period_starts_at less than the specified date
   */
  filterPayPeriodStartsAtLt?: Date | undefined;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  filterBy?: string | undefined;
};

export type ListPaychecksResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the paycheck object.
   */
  paychecksData?: models.PaychecksData | undefined;
};

/** @internal */
export type ListPaychecksRequest$Outbound = {
  "filter[job.id]"?: string | undefined;
  "filter[status]"?: string | undefined;
  "filter[deposit_expected_at__gte]"?: string | undefined;
  "filter[deposit_expected_at__lt]"?: string | undefined;
  "filter[pay_period_ends_at__gte]"?: string | undefined;
  "filter[pay_period_ends_at__lt]"?: string | undefined;
  "filter[pay_period_starts_at__gte]"?: string | undefined;
  "filter[pay_period_starts_at__lt]"?: string | undefined;
  "filter-by"?: string | undefined;
};

/** @internal */
export const ListPaychecksRequest$outboundSchema: z.ZodType<
  ListPaychecksRequest$Outbound,
  z.ZodTypeDef,
  ListPaychecksRequest
> = z.object({
  filterJobId: z.string().optional(),
  filterStatus: models.FilterPaycheckStatus$outboundSchema.optional(),
  filterDepositExpectedAtGte: z.date().transform(v => v.toISOString())
    .optional(),
  filterDepositExpectedAtLt: z.date().transform(v => v.toISOString())
    .optional(),
  filterPayPeriodEndsAtGte: z.date().transform(v => v.toISOString()).optional(),
  filterPayPeriodEndsAtLt: z.date().transform(v => v.toISOString()).optional(),
  filterPayPeriodStartsAtGte: z.date().transform(v => v.toISOString())
    .optional(),
  filterPayPeriodStartsAtLt: z.date().transform(v => v.toISOString())
    .optional(),
  filterBy: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterJobId: "filter[job.id]",
    filterStatus: "filter[status]",
    filterDepositExpectedAtGte: "filter[deposit_expected_at__gte]",
    filterDepositExpectedAtLt: "filter[deposit_expected_at__lt]",
    filterPayPeriodEndsAtGte: "filter[pay_period_ends_at__gte]",
    filterPayPeriodEndsAtLt: "filter[pay_period_ends_at__lt]",
    filterPayPeriodStartsAtGte: "filter[pay_period_starts_at__gte]",
    filterPayPeriodStartsAtLt: "filter[pay_period_starts_at__lt]",
    filterBy: "filter-by",
  });
});

export function listPaychecksRequestToJSON(
  listPaychecksRequest: ListPaychecksRequest,
): string {
  return JSON.stringify(
    ListPaychecksRequest$outboundSchema.parse(listPaychecksRequest),
  );
}

/** @internal */
export const ListPaychecksResponse$inboundSchema: z.ZodType<
  ListPaychecksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  PaychecksData: models.PaychecksData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "PaychecksData": "paychecksData",
  });
});

export function listPaychecksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPaychecksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPaychecksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPaychecksResponse' from JSON`,
  );
}
