/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListAccountsGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ListAccountsRequest = {
  /**
   * Limit the results to documents related to a specific person
   */
  filterPersonId?: string | undefined;
  /**
   * Limit the results to documents matching the specified account type.
   */
  filterAccountType?: models.FilterAccountType | undefined;
  /**
   * Limit the results to documents matching the specified account subtype.
   */
  filterSubtype?: string | undefined;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  filterBy?: string | undefined;
};

export type ListAccountsResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the account object.
   */
  accountsData?: models.AccountsData | undefined;
};

/** @internal */
export type ListAccountsRequest$Outbound = {
  "filter[person.id]"?: string | undefined;
  "filter[account_type]"?: string | undefined;
  "filter[subtype]"?: string | undefined;
  "filter-by"?: string | undefined;
};

/** @internal */
export const ListAccountsRequest$outboundSchema: z.ZodType<
  ListAccountsRequest$Outbound,
  z.ZodTypeDef,
  ListAccountsRequest
> = z.object({
  filterPersonId: z.string().optional(),
  filterAccountType: models.FilterAccountType$outboundSchema.optional(),
  filterSubtype: z.string().optional(),
  filterBy: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterPersonId: "filter[person.id]",
    filterAccountType: "filter[account_type]",
    filterSubtype: "filter[subtype]",
    filterBy: "filter-by",
  });
});

export function listAccountsRequestToJSON(
  listAccountsRequest: ListAccountsRequest,
): string {
  return JSON.stringify(
    ListAccountsRequest$outboundSchema.parse(listAccountsRequest),
  );
}

/** @internal */
export const ListAccountsResponse$inboundSchema: z.ZodType<
  ListAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  AccountsData: models.AccountsData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "AccountsData": "accountsData",
  });
});

export function listAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAccountsResponse' from JSON`,
  );
}
