/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListJobsGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ListJobsRequest = {
  /**
   * Limit the results to documents with an external identifier matching exactly at the specified key.
   */
  filterExternalIdentifiersPrimaryIdentifier?: string | undefined;
  /**
   * Limit the results to documents with an external identifier matching exactly at the specified key.
   */
  filterExternalIdentifiersEmployeeId?: string | undefined;
  /**
   * Limit the results to documents with an external identifier matching exactly at the specified key.
   */
  filterExternalIdentifiersGroup?: string | undefined;
  /**
   * Limit the results to documents related to a specific person
   */
  filterPersonId?: string | undefined;
  /**
   * _Not yet supported_ Limit the results to documents related to a specific organization
   */
  filterOrganizationId?: string | undefined;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  filterBy?: string | undefined;
};

export type ListJobsResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns a list of job objects.
   */
  jobsData?: models.JobsData | undefined;
};

/** @internal */
export type ListJobsRequest$Outbound = {
  "filter[external_identifiers.primary_identifier]"?: string | undefined;
  "filter[external_identifiers.employee_id]"?: string | undefined;
  "filter[external_identifiers.group]"?: string | undefined;
  "filter[person.id]"?: string | undefined;
  "filter[organization.id]"?: string | undefined;
  "filter-by"?: string | undefined;
};

/** @internal */
export const ListJobsRequest$outboundSchema: z.ZodType<
  ListJobsRequest$Outbound,
  z.ZodTypeDef,
  ListJobsRequest
> = z.object({
  filterExternalIdentifiersPrimaryIdentifier: z.string().optional(),
  filterExternalIdentifiersEmployeeId: z.string().optional(),
  filterExternalIdentifiersGroup: z.string().optional(),
  filterPersonId: z.string().optional(),
  filterOrganizationId: z.string().optional(),
  filterBy: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterExternalIdentifiersPrimaryIdentifier:
      "filter[external_identifiers.primary_identifier]",
    filterExternalIdentifiersEmployeeId:
      "filter[external_identifiers.employee_id]",
    filterExternalIdentifiersGroup: "filter[external_identifiers.group]",
    filterPersonId: "filter[person.id]",
    filterOrganizationId: "filter[organization.id]",
    filterBy: "filter-by",
  });
});

export function listJobsRequestToJSON(
  listJobsRequest: ListJobsRequest,
): string {
  return JSON.stringify(ListJobsRequest$outboundSchema.parse(listJobsRequest));
}

/** @internal */
export const ListJobsResponse$inboundSchema: z.ZodType<
  ListJobsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  JobsData: models.JobsData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "JobsData": "jobsData",
  });
});

export function listJobsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListJobsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListJobsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListJobsResponse' from JSON`,
  );
}
