/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListOrganizationsGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ListOrganizationsRequest = {
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  filterBy?: string | undefined;
};

export type ListOrganizationsResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns a list of organization objects that match the filter. If no organizations match the filter, the resulting collection will be empty. If no filter is provider, the resulting collection will include all accessible organizations.
   */
  organizationsData?: models.OrganizationsData | undefined;
};

/** @internal */
export type ListOrganizationsRequest$Outbound = {
  "filter-by"?: string | undefined;
};

/** @internal */
export const ListOrganizationsRequest$outboundSchema: z.ZodType<
  ListOrganizationsRequest$Outbound,
  z.ZodTypeDef,
  ListOrganizationsRequest
> = z.object({
  filterBy: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterBy: "filter-by",
  });
});

export function listOrganizationsRequestToJSON(
  listOrganizationsRequest: ListOrganizationsRequest,
): string {
  return JSON.stringify(
    ListOrganizationsRequest$outboundSchema.parse(listOrganizationsRequest),
  );
}

/** @internal */
export const ListOrganizationsResponse$inboundSchema: z.ZodType<
  ListOrganizationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  OrganizationsData: models.OrganizationsData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "OrganizationsData": "organizationsData",
  });
});

export function listOrganizationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsResponse' from JSON`,
  );
}
