/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ReadJobGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ReadJobRequest = {
  /**
   * Unique ID of the job
   */
  jobId: string;
};

export type ReadJobResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the job object.
   */
  jobData?: models.JobData | undefined;
};

/** @internal */
export type ReadJobRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const ReadJobRequest$outboundSchema: z.ZodType<
  ReadJobRequest$Outbound,
  z.ZodTypeDef,
  ReadJobRequest
> = z.object({
  jobId: z.string(),
}).transform((v) => {
  return remap$(v, {
    jobId: "job_id",
  });
});

export function readJobRequestToJSON(readJobRequest: ReadJobRequest): string {
  return JSON.stringify(ReadJobRequest$outboundSchema.parse(readJobRequest));
}

/** @internal */
export const ReadJobResponse$inboundSchema: z.ZodType<
  ReadJobResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  JobData: models.JobData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "JobData": "jobData",
  });
});

export function readJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReadJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadJobResponse' from JSON`,
  );
}
