/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ReadPersonGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ReadPersonRequest = {
  /**
   * Unique ID of the person
   */
  personId: string;
};

export type ReadPersonResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the person object.
   */
  personData?: models.PersonData | undefined;
};

/** @internal */
export type ReadPersonRequest$Outbound = {
  person_id: string;
};

/** @internal */
export const ReadPersonRequest$outboundSchema: z.ZodType<
  ReadPersonRequest$Outbound,
  z.ZodTypeDef,
  ReadPersonRequest
> = z.object({
  personId: z.string(),
}).transform((v) => {
  return remap$(v, {
    personId: "person_id",
  });
});

export function readPersonRequestToJSON(
  readPersonRequest: ReadPersonRequest,
): string {
  return JSON.stringify(
    ReadPersonRequest$outboundSchema.parse(readPersonRequest),
  );
}

/** @internal */
export const ReadPersonResponse$inboundSchema: z.ZodType<
  ReadPersonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  PersonData: models.PersonData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "PersonData": "personData",
  });
});

export function readPersonResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReadPersonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadPersonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadPersonResponse' from JSON`,
  );
}
