/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ReadPaycheckGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ReadPaycheckRequest = {
  /**
   * Unique ID of the paycheck
   */
  paycheckId: string;
};

export type ReadPaycheckResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the paycheck object.
   */
  paycheckData?: models.PaycheckData | undefined;
};

/** @internal */
export type ReadPaycheckRequest$Outbound = {
  paycheck_id: string;
};

/** @internal */
export const ReadPaycheckRequest$outboundSchema: z.ZodType<
  ReadPaycheckRequest$Outbound,
  z.ZodTypeDef,
  ReadPaycheckRequest
> = z.object({
  paycheckId: z.string(),
}).transform((v) => {
  return remap$(v, {
    paycheckId: "paycheck_id",
  });
});

export function readPaycheckRequestToJSON(
  readPaycheckRequest: ReadPaycheckRequest,
): string {
  return JSON.stringify(
    ReadPaycheckRequest$outboundSchema.parse(readPaycheckRequest),
  );
}

/** @internal */
export const ReadPaycheckResponse$inboundSchema: z.ZodType<
  ReadPaycheckResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  PaycheckData: models.PaycheckData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "PaycheckData": "paycheckData",
  });
});

export function readPaycheckResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReadPaycheckResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadPaycheckResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadPaycheckResponse' from JSON`,
  );
}
