/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ReadAccountGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ReadAccountRequest = {
  /**
   * Unique UUID of the Account.
   */
  accountId: string;
};

export type ReadAccountResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the account object.
   */
  accountData?: models.AccountData | undefined;
};

/** @internal */
export type ReadAccountRequest$Outbound = {
  account_id: string;
};

/** @internal */
export const ReadAccountRequest$outboundSchema: z.ZodType<
  ReadAccountRequest$Outbound,
  z.ZodTypeDef,
  ReadAccountRequest
> = z.object({
  accountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
  });
});

export function readAccountRequestToJSON(
  readAccountRequest: ReadAccountRequest,
): string {
  return JSON.stringify(
    ReadAccountRequest$outboundSchema.parse(readAccountRequest),
  );
}

/** @internal */
export const ReadAccountResponse$inboundSchema: z.ZodType<
  ReadAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  AccountData: models.AccountData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "AccountData": "accountData",
  });
});

export function readAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReadAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadAccountResponse' from JSON`,
  );
}
