/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateJobGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type UpdateJobRequest = {
  /**
   * Unique ID of the job
   */
  jobId: string;
  jobUpdateData: models.JobUpdateData;
};

export type UpdateJobResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Returns the updated Job object
   */
  jobData?: models.JobData | undefined;
};

/** @internal */
export type UpdateJobRequest$Outbound = {
  job_id: string;
  JobUpdateData: models.JobUpdateData$Outbound;
};

/** @internal */
export const UpdateJobRequest$outboundSchema: z.ZodType<
  UpdateJobRequest$Outbound,
  z.ZodTypeDef,
  UpdateJobRequest
> = z.object({
  jobId: z.string(),
  jobUpdateData: models.JobUpdateData$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    jobId: "job_id",
    jobUpdateData: "JobUpdateData",
  });
});

export function updateJobRequestToJSON(
  updateJobRequest: UpdateJobRequest,
): string {
  return JSON.stringify(
    UpdateJobRequest$outboundSchema.parse(updateJobRequest),
  );
}

/** @internal */
export const UpdateJobResponse$inboundSchema: z.ZodType<
  UpdateJobResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: models.HTTPMetadata$inboundSchema,
  JobData: models.JobData$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "JobData": "jobData",
  });
});

export function updateJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateJobResponse' from JSON`,
  );
}
