// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountCreateData struct {
	Data AccountCreateResource `json:"data"`
}

func (o *AccountCreateData) GetData() AccountCreateResource {
	if o == nil {
		return AccountCreateResource{}
	}
	return o.Data
}
