// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type AccountCreateResource struct {
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountCreateAttributes `json:"attributes"`
	Relationships AccountRelationships    `json:"relationships"`
}

func (a AccountCreateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountCreateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type", "attributes", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (o *AccountCreateResource) GetType() string {
	return "accounts"
}

func (o *AccountCreateResource) GetAttributes() AccountCreateAttributes {
	if o == nil {
		return AccountCreateAttributes{}
	}
	return o.Attributes
}

func (o *AccountCreateResource) GetAttributesCard() *AccountCreateAttributesCard {
	return o.GetAttributes().AccountCreateAttributesCard
}

func (o *AccountCreateResource) GetAttributesDepository() *AccountCreateAttributesDepository {
	return o.GetAttributes().AccountCreateAttributesDepository
}

func (o *AccountCreateResource) GetRelationships() AccountRelationships {
	if o == nil {
		return AccountRelationships{}
	}
	return o.Relationships
}
