// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type AccountResource struct {
	// The unique identifier of the Account.
	ID string `json:"id"`
	// The type of the resource. Always `accounts`.
	type_ string `const:"accounts" json:"type"`
	// The details of the account.
	Attributes    AccountAttributes    `json:"attributes"`
	Links         AccountLinks         `json:"links"`
	Relationships AccountRelationships `json:"relationships"`
}

func (a AccountResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"id", "type", "attributes", "links", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (o *AccountResource) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccountResource) GetType() string {
	return "accounts"
}

func (o *AccountResource) GetAttributes() AccountAttributes {
	if o == nil {
		return AccountAttributes{}
	}
	return o.Attributes
}

func (o *AccountResource) GetAttributesCard() *Card {
	return o.GetAttributes().Card
}

func (o *AccountResource) GetAttributesEarningsBalance() *EarningsBalanceReadOnly {
	return o.GetAttributes().EarningsBalanceReadOnly
}

func (o *AccountResource) GetAttributesDepository() *Depository {
	return o.GetAttributes().Depository
}

func (o *AccountResource) GetLinks() AccountLinks {
	if o == nil {
		return AccountLinks{}
	}
	return o.Links
}

func (o *AccountResource) GetRelationships() AccountRelationships {
	if o == nil {
		return AccountRelationships{}
	}
	return o.Relationships
}
