// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountsData - Returns the account object.
type AccountsData struct {
	Data []AccountResource `json:"data"`
}

func (o *AccountsData) GetData() []AccountResource {
	if o == nil {
		return []AccountResource{}
	}
	return o.Data
}
