// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// AccountCreateAttributesCardSubtype - The subtype of the account. Additional subtypes may be added over time
type AccountCreateAttributesCardSubtype string

const (
	AccountCreateAttributesCardSubtypeDebit    AccountCreateAttributesCardSubtype = "DEBIT"
	AccountCreateAttributesCardSubtypeDailypay AccountCreateAttributesCardSubtype = "DAILYPAY"
)

func (e AccountCreateAttributesCardSubtype) ToPointer() *AccountCreateAttributesCardSubtype {
	return &e
}
func (e *AccountCreateAttributesCardSubtype) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DEBIT":
		fallthrough
	case "DAILYPAY":
		*e = AccountCreateAttributesCardSubtype(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountCreateAttributesCardSubtype: %v", v)
	}
}

// CreateCardAccountDetails - The banking details of the account and account holder.
type CreateCardAccountDetails struct {
	// A tokenized string replacement for the card data.
	Token string `json:"token"`
	// The first name of the account holder.
	FirstName string `json:"first_name"`
	// The last name of the account holder.
	LastName string `json:"last_name"`
	// The month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The year of the expiration date for the card.
	ExpirationYear string `json:"expiration_year"`
	// The first line of the address for the card.
	AddressLineOne string `json:"address_line_one"`
	// The second line of the address for the card.
	AddressLineTwo *string `json:"address_line_two,omitempty"`
	// The city of the address for the card.
	AddressCity string `json:"address_city"`
	// The two-letter abbreviation of the state in the address for the card.
	AddressState string `json:"address_state"`
	// The zip code of the address for the card.
	AddressZipCode string `json:"address_zip_code"`
	// The country code of the address for the card.
	AddressCountry string `json:"address_country"`
	// The issuer of the card.
	Issuer string `json:"issuer"`
}

func (c CreateCardAccountDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCardAccountDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"token", "first_name", "last_name", "expiration_month", "expiration_year", "address_line_one", "address_city", "address_state", "address_zip_code", "address_country", "issuer"}); err != nil {
		return err
	}
	return nil
}

func (o *CreateCardAccountDetails) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *CreateCardAccountDetails) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *CreateCardAccountDetails) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *CreateCardAccountDetails) GetExpirationMonth() string {
	if o == nil {
		return ""
	}
	return o.ExpirationMonth
}

func (o *CreateCardAccountDetails) GetExpirationYear() string {
	if o == nil {
		return ""
	}
	return o.ExpirationYear
}

func (o *CreateCardAccountDetails) GetAddressLineOne() string {
	if o == nil {
		return ""
	}
	return o.AddressLineOne
}

func (o *CreateCardAccountDetails) GetAddressLineTwo() *string {
	if o == nil {
		return nil
	}
	return o.AddressLineTwo
}

func (o *CreateCardAccountDetails) GetAddressCity() string {
	if o == nil {
		return ""
	}
	return o.AddressCity
}

func (o *CreateCardAccountDetails) GetAddressState() string {
	if o == nil {
		return ""
	}
	return o.AddressState
}

func (o *CreateCardAccountDetails) GetAddressZipCode() string {
	if o == nil {
		return ""
	}
	return o.AddressZipCode
}

func (o *CreateCardAccountDetails) GetAddressCountry() string {
	if o == nil {
		return ""
	}
	return o.AddressCountry
}

func (o *CreateCardAccountDetails) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}

// AccountCreateAttributesCard - An account with type `CARD` and subtype `DAILYPAY` or `DEBIT`.
type AccountCreateAttributesCard struct {
	// Display name for this account.
	Name string `json:"name"`
	// The type of account. It differentiates between depository accounts (e.g. bank account), cards (e.g. debit) and earnings balance type of accounts (e.g. on demand pay).
	accountType string `const:"CARD" json:"account_type"`
	// The subtype of the account. Additional subtypes may be added over time
	Subtype AccountCreateAttributesCardSubtype `json:"subtype"`
	// The banking details of the account and account holder.
	CreateCardAccountDetails CreateCardAccountDetails `json:"details"`
}

func (a AccountCreateAttributesCard) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountCreateAttributesCard) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"name", "account_type", "subtype", "details"}); err != nil {
		return err
	}
	return nil
}

func (o *AccountCreateAttributesCard) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AccountCreateAttributesCard) GetAccountType() string {
	return "CARD"
}

func (o *AccountCreateAttributesCard) GetSubtype() AccountCreateAttributesCardSubtype {
	if o == nil {
		return AccountCreateAttributesCardSubtype("")
	}
	return o.Subtype
}

func (o *AccountCreateAttributesCard) GetCreateCardAccountDetails() CreateCardAccountDetails {
	if o == nil {
		return CreateCardAccountDetails{}
	}
	return o.CreateCardAccountDetails
}
