// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type AccountIdentifier struct {
	type_ string `const:"accounts" json:"type"`
	ID    string `json:"id"`
}

func (a AccountIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (o *AccountIdentifier) GetType() string {
	return "accounts"
}

func (o *AccountIdentifier) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
