// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountData - Returns the account object.
type AccountData struct {
	Data AccountResource `json:"data"`
}

func (o *AccountData) GetData() AccountResource {
	if o == nil {
		return AccountResource{}
	}
	return o.Data
}
