// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorBadRequestErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorBadRequestErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (o *ErrorBadRequestErrorLinks) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

// ErrorBadRequestErrorSource - Location in the request that may have caused the error.
type ErrorBadRequestErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (o *ErrorBadRequestErrorSource) GetParameter() *string {
	if o == nil {
		return nil
	}
	return o.Parameter
}

func (o *ErrorBadRequestErrorSource) GetPointer() *string {
	if o == nil {
		return nil
	}
	return o.Pointer
}

func (o *ErrorBadRequestErrorSource) GetHeader() *string {
	if o == nil {
		return nil
	}
	return o.Header
}

// ErrorBadRequestErrorMeta - Additional information about the error.
type ErrorBadRequestErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (o *ErrorBadRequestErrorMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *ErrorBadRequestErrorMeta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

type ErrorBadRequestError struct {
	// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorBadRequestErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorBadRequestErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorBadRequestErrorMeta `json:"meta"`
}

func (o *ErrorBadRequestError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *ErrorBadRequestError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ErrorBadRequestError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ErrorBadRequestError) GetLinks() ErrorBadRequestErrorLinks {
	if o == nil {
		return ErrorBadRequestErrorLinks{}
	}
	return o.Links
}

func (o *ErrorBadRequestError) GetSource() *ErrorBadRequestErrorSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ErrorBadRequestError) GetMeta() ErrorBadRequestErrorMeta {
	if o == nil {
		return ErrorBadRequestErrorMeta{}
	}
	return o.Meta
}
