// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorJobUpdateErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorJobUpdateErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (o *ErrorJobUpdateErrorLinks) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

// ErrorJobUpdateErrorSource - Location in the request that may have caused the error.
type ErrorJobUpdateErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (o *ErrorJobUpdateErrorSource) GetParameter() *string {
	if o == nil {
		return nil
	}
	return o.Parameter
}

func (o *ErrorJobUpdateErrorSource) GetPointer() *string {
	if o == nil {
		return nil
	}
	return o.Pointer
}

func (o *ErrorJobUpdateErrorSource) GetHeader() *string {
	if o == nil {
		return nil
	}
	return o.Header
}

// ErrorJobUpdateErrorMeta - Additional information about the error.
type ErrorJobUpdateErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (o *ErrorJobUpdateErrorMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *ErrorJobUpdateErrorMeta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

type ErrorJobUpdateError struct {
	// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorJobUpdateErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorJobUpdateErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorJobUpdateErrorMeta `json:"meta"`
}

func (o *ErrorJobUpdateError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *ErrorJobUpdateError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ErrorJobUpdateError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ErrorJobUpdateError) GetLinks() ErrorJobUpdateErrorLinks {
	if o == nil {
		return ErrorJobUpdateErrorLinks{}
	}
	return o.Links
}

func (o *ErrorJobUpdateError) GetSource() *ErrorJobUpdateErrorSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ErrorJobUpdateError) GetMeta() ErrorJobUpdateErrorMeta {
	if o == nil {
		return ErrorJobUpdateErrorMeta{}
	}
	return o.Meta
}
