// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorTransferCreateErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorTransferCreateErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (o *ErrorTransferCreateErrorLinks) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

// ErrorTransferCreateErrorSource - Location in the request that may have caused the error.
type ErrorTransferCreateErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (o *ErrorTransferCreateErrorSource) GetParameter() *string {
	if o == nil {
		return nil
	}
	return o.Parameter
}

func (o *ErrorTransferCreateErrorSource) GetPointer() *string {
	if o == nil {
		return nil
	}
	return o.Pointer
}

func (o *ErrorTransferCreateErrorSource) GetHeader() *string {
	if o == nil {
		return nil
	}
	return o.Header
}

// ErrorTransferCreateErrorMeta - Additional information about the error.
type ErrorTransferCreateErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (o *ErrorTransferCreateErrorMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *ErrorTransferCreateErrorMeta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

type ErrorTransferCreateError struct {
	// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
	Code string `json:"code"`
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorTransferCreateErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorTransferCreateErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorTransferCreateErrorMeta `json:"meta"`
}

func (o *ErrorTransferCreateError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *ErrorTransferCreateError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ErrorTransferCreateError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ErrorTransferCreateError) GetLinks() ErrorTransferCreateErrorLinks {
	if o == nil {
		return ErrorTransferCreateErrorLinks{}
	}
	return o.Links
}

func (o *ErrorTransferCreateError) GetSource() *ErrorTransferCreateErrorSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ErrorTransferCreateError) GetMeta() ErrorTransferCreateErrorMeta {
	if o == nil {
		return ErrorTransferCreateErrorMeta{}
	}
	return o.Meta
}
