// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ErrorForbiddenErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorForbiddenErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (o *ErrorForbiddenErrorLinks) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

// ErrorForbiddenErrorSource - Location in the request that may have caused the error.
type ErrorForbiddenErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (o *ErrorForbiddenErrorSource) GetParameter() *string {
	if o == nil {
		return nil
	}
	return o.Parameter
}

func (o *ErrorForbiddenErrorSource) GetPointer() *string {
	if o == nil {
		return nil
	}
	return o.Pointer
}

func (o *ErrorForbiddenErrorSource) GetHeader() *string {
	if o == nil {
		return nil
	}
	return o.Header
}

// ErrorForbiddenErrorMeta - Additional information about the error.
type ErrorForbiddenErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (o *ErrorForbiddenErrorMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *ErrorForbiddenErrorMeta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

// ErrorForbiddenErrorCode - A code that indicates what went wrong.
type ErrorForbiddenErrorCode string

const (
	ErrorForbiddenErrorCodeForbidden ErrorForbiddenErrorCode = "FORBIDDEN"
)

func (e ErrorForbiddenErrorCode) ToPointer() *ErrorForbiddenErrorCode {
	return &e
}
func (e *ErrorForbiddenErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FORBIDDEN":
		*e = ErrorForbiddenErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorForbiddenErrorCode: %v", v)
	}
}

type ErrorForbiddenError struct {
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorForbiddenErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorForbiddenErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorForbiddenErrorMeta `json:"meta"`
	// A code that indicates what went wrong.
	Code ErrorForbiddenErrorCode `json:"code"`
}

func (o *ErrorForbiddenError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ErrorForbiddenError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ErrorForbiddenError) GetLinks() ErrorForbiddenErrorLinks {
	if o == nil {
		return ErrorForbiddenErrorLinks{}
	}
	return o.Links
}

func (o *ErrorForbiddenError) GetSource() *ErrorForbiddenErrorSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ErrorForbiddenError) GetMeta() ErrorForbiddenErrorMeta {
	if o == nil {
		return ErrorForbiddenErrorMeta{}
	}
	return o.Meta
}

func (o *ErrorForbiddenError) GetCode() ErrorForbiddenErrorCode {
	if o == nil {
		return ErrorForbiddenErrorCode("")
	}
	return o.Code
}
