// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ErrorUnauthorizedErrorLinks - A list of links to resources that may be helpful in resolving the error.
type ErrorUnauthorizedErrorLinks struct {
	About *string `json:"about,omitempty"`
}

func (o *ErrorUnauthorizedErrorLinks) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

// ErrorUnauthorizedErrorSource - Location in the request that may have caused the error.
type ErrorUnauthorizedErrorSource struct {
	// The name of the parameter that caused the error.
	Parameter *string `json:"parameter,omitempty"`
	// A JSON Pointer to the location in the request that caused the error.
	Pointer *string `json:"pointer,omitempty"`
	// The name of the header that caused the error.
	Header *string `json:"header,omitempty"`
}

func (o *ErrorUnauthorizedErrorSource) GetParameter() *string {
	if o == nil {
		return nil
	}
	return o.Parameter
}

func (o *ErrorUnauthorizedErrorSource) GetPointer() *string {
	if o == nil {
		return nil
	}
	return o.Pointer
}

func (o *ErrorUnauthorizedErrorSource) GetHeader() *string {
	if o == nil {
		return nil
	}
	return o.Header
}

// ErrorUnauthorizedErrorMeta - Additional information about the error.
type ErrorUnauthorizedErrorMeta struct {
	// A UUID for the originating request.
	RequestID *string `json:"request_id,omitempty"`
	// An ID used for tracing purposes.
	TraceID *string `json:"trace_id,omitempty"`
}

func (o *ErrorUnauthorizedErrorMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *ErrorUnauthorizedErrorMeta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

// ErrorUnauthorizedErrorCode - A code that indicates what went wrong.
type ErrorUnauthorizedErrorCode string

const (
	ErrorUnauthorizedErrorCodeInvalidToken ErrorUnauthorizedErrorCode = "INVALID_TOKEN"
	ErrorUnauthorizedErrorCodeUnauthorized ErrorUnauthorizedErrorCode = "UNAUTHORIZED"
)

func (e ErrorUnauthorizedErrorCode) ToPointer() *ErrorUnauthorizedErrorCode {
	return &e
}
func (e *ErrorUnauthorizedErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INVALID_TOKEN":
		fallthrough
	case "UNAUTHORIZED":
		*e = ErrorUnauthorizedErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorUnauthorizedErrorCode: %v", v)
	}
}

type ErrorUnauthorizedError struct {
	// The HTTP status code for the error.
	Status string `json:"status"`
	// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
	Detail string `json:"detail"`
	// A list of links to resources that may be helpful in resolving the error.
	Links ErrorUnauthorizedErrorLinks `json:"links"`
	// Location in the request that may have caused the error.
	Source *ErrorUnauthorizedErrorSource `json:"source,omitempty"`
	// Additional information about the error.
	Meta ErrorUnauthorizedErrorMeta `json:"meta"`
	// A code that indicates what went wrong.
	Code ErrorUnauthorizedErrorCode `json:"code"`
}

func (o *ErrorUnauthorizedError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ErrorUnauthorizedError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ErrorUnauthorizedError) GetLinks() ErrorUnauthorizedErrorLinks {
	if o == nil {
		return ErrorUnauthorizedErrorLinks{}
	}
	return o.Links
}

func (o *ErrorUnauthorizedError) GetSource() *ErrorUnauthorizedErrorSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ErrorUnauthorizedError) GetMeta() ErrorUnauthorizedErrorMeta {
	if o == nil {
		return ErrorUnauthorizedErrorMeta{}
	}
	return o.Meta
}

func (o *ErrorUnauthorizedError) GetCode() ErrorUnauthorizedErrorCode {
	if o == nil {
		return ErrorUnauthorizedErrorCode("")
	}
	return o.Code
}
