// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type FilterPaycheckStatus string

const (
	FilterPaycheckStatusEstimated  FilterPaycheckStatus = "ESTIMATED"
	FilterPaycheckStatusProcessing FilterPaycheckStatus = "PROCESSING"
	FilterPaycheckStatusInTransit  FilterPaycheckStatus = "IN_TRANSIT"
	FilterPaycheckStatusDeposited  FilterPaycheckStatus = "DEPOSITED"
)

func (e FilterPaycheckStatus) ToPointer() *FilterPaycheckStatus {
	return &e
}
func (e *FilterPaycheckStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ESTIMATED":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "IN_TRANSIT":
		fallthrough
	case "DEPOSITED":
		*e = FilterPaycheckStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterPaycheckStatus: %v", v)
	}
}
