// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type FilterAccountType string

const (
	FilterAccountTypeEarningsBalance FilterAccountType = "EARNINGS_BALANCE"
	FilterAccountTypeDepository      FilterAccountType = "DEPOSITORY"
	FilterAccountTypeCard            FilterAccountType = "CARD"
)

func (e FilterAccountType) ToPointer() *FilterAccountType {
	return &e
}
func (e *FilterAccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EARNINGS_BALANCE":
		fallthrough
	case "DEPOSITORY":
		fallthrough
	case "CARD":
		*e = FilterAccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterAccountType: %v", v)
	}
}
