// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type FundingSourceIdentifier struct {
	type_ string `const:"funding_sources" json:"type"`
	ID    string `json:"id"`
}

func (f FundingSourceIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FundingSourceIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (o *FundingSourceIdentifier) GetType() string {
	return "funding_sources"
}

func (o *FundingSourceIdentifier) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
