// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundingSourceRelationships struct {
	Source   PaycheckRelationship `json:"source"`
	Transfer TransferRelationship `json:"transfer"`
}

func (o *FundingSourceRelationships) GetSource() PaycheckRelationship {
	if o == nil {
		return PaycheckRelationship{}
	}
	return o.Source
}

func (o *FundingSourceRelationships) GetTransfer() TransferRelationship {
	if o == nil {
		return TransferRelationship{}
	}
	return o.Transfer
}
