// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundingSourcesRelationship struct {
	Data []FundingSourceIdentifier `json:"data"`
}

func (o *FundingSourcesRelationship) GetData() []FundingSourceIdentifier {
	if o == nil {
		return []FundingSourceIdentifier{}
	}
	return o.Data
}
