// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobData - Returns the job object.
type JobData struct {
	// A job describes the financial relationship between a person and an organization.
	Data JobResource `json:"data"`
}

func (o *JobData) GetData() JobResource {
	if o == nil {
		return JobResource{}
	}
	return o.Data
}
