// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type JobIdentifier struct {
	type_ string `const:"jobs" json:"type"`
	ID    string `json:"id"`
}

func (j JobIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JobIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (o *JobIdentifier) GetType() string {
	return "jobs"
}

func (o *JobIdentifier) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
