// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobRelationships - The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
type JobRelationships struct {
	Person                         PersonRelationship       `json:"person"`
	Organization                   OrganizationRelationship `json:"organization"`
	DirectDepositDefaultDepository *AccountRelationship     `json:"direct_deposit_default_depository,omitempty"`
	DirectDepositDefaultCard       *AccountRelationship     `json:"direct_deposit_default_card,omitempty"`
}

func (o *JobRelationships) GetPerson() PersonRelationship {
	if o == nil {
		return PersonRelationship{}
	}
	return o.Person
}

func (o *JobRelationships) GetOrganization() OrganizationRelationship {
	if o == nil {
		return OrganizationRelationship{}
	}
	return o.Organization
}

func (o *JobRelationships) GetDirectDepositDefaultDepository() *AccountRelationship {
	if o == nil {
		return nil
	}
	return o.DirectDepositDefaultDepository
}

func (o *JobRelationships) GetDirectDepositDefaultCard() *AccountRelationship {
	if o == nil {
		return nil
	}
	return o.DirectDepositDefaultCard
}
