// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobRelationship struct {
	Data JobIdentifier `json:"data"`
}

func (o *JobRelationship) GetData() JobIdentifier {
	if o == nil {
		return JobIdentifier{}
	}
	return o.Data
}
