// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JobsData - Returns a list of job objects.
type JobsData struct {
	Data []JobResource `json:"data"`
}

func (o *JobsData) GetData() []JobResource {
	if o == nil {
		return []JobResource{}
	}
	return o.Data
}
