// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type OrganizationIdentifier struct {
	type_ string `const:"organizations" json:"type"`
	ID    string `json:"id"`
}

func (o OrganizationIdentifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationIdentifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationIdentifier) GetType() string {
	return "organizations"
}

func (o *OrganizationIdentifier) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
