// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrganizationLinks struct {
	Self string `json:"self"`
}

func (o *OrganizationLinks) GetSelf() string {
	if o == nil {
		return ""
	}
	return o.Self
}
