// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OrganizationsData - Returns a list of organization objects that match the filter. If no organizations match the filter, the resulting collection will be empty. If no filter is provider, the resulting collection will include all accessible organizations.
type OrganizationsData struct {
	Data []OrganizationResource `json:"data"`
}

func (o *OrganizationsData) GetData() []OrganizationResource {
	if o == nil {
		return []OrganizationResource{}
	}
	return o.Data
}
