// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrganizationAttributes struct {
	// Organization's name
	Name *string `json:"name,omitempty"`
	// List of the names of products available for this organization.
	Products []string `json:"products,omitempty"`
}

func (o *OrganizationAttributes) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OrganizationAttributes) GetProducts() []string {
	if o == nil {
		return nil
	}
	return o.Products
}
