// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrganizationRelationship struct {
	Data OrganizationIdentifier `json:"data"`
}

func (o *OrganizationRelationship) GetData() OrganizationIdentifier {
	if o == nil {
		return OrganizationIdentifier{}
	}
	return o.Data
}
