// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaycheckRelationships struct {
	Person PersonRelationship `json:"person"`
	Job    JobRelationship    `json:"job"`
}

func (o *PaycheckRelationships) GetPerson() PersonRelationship {
	if o == nil {
		return PersonRelationship{}
	}
	return o.Person
}

func (o *PaycheckRelationships) GetJob() JobRelationship {
	if o == nil {
		return JobRelationship{}
	}
	return o.Job
}
