// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type PaycheckResource struct {
	type_         string                `const:"paychecks" json:"type"`
	ID            string                `json:"id"`
	Attributes    PaycheckAttributes    `json:"attributes"`
	Links         PaycheckLinks         `json:"links"`
	Relationships PaycheckRelationships `json:"relationships"`
}

func (p PaycheckResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaycheckResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "id", "attributes", "links", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (o *PaycheckResource) GetType() string {
	return "paychecks"
}

func (o *PaycheckResource) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PaycheckResource) GetAttributes() PaycheckAttributes {
	if o == nil {
		return PaycheckAttributes{}
	}
	return o.Attributes
}

func (o *PaycheckResource) GetLinks() PaycheckLinks {
	if o == nil {
		return PaycheckLinks{}
	}
	return o.Links
}

func (o *PaycheckResource) GetRelationships() PaycheckRelationships {
	if o == nil {
		return PaycheckRelationships{}
	}
	return o.Relationships
}
