// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaycheckData - Returns the paycheck object.
type PaycheckData struct {
	Data PaycheckResource `json:"data"`
}

func (o *PaycheckData) GetData() PaycheckResource {
	if o == nil {
		return PaycheckResource{}
	}
	return o.Data
}
