// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type PaycheckRelationship struct {
	Data PaycheckIdentifier `json:"data"`
}

func (p PaycheckRelationship) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaycheckRelationship) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"data"}); err != nil {
		return err
	}
	return nil
}

func (o *PaycheckRelationship) GetData() PaycheckIdentifier {
	if o == nil {
		return PaycheckIdentifier{}
	}
	return o.Data
}
