// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PersonData - Returns the person object.
type PersonData struct {
	Data PersonResource `json:"data"`
}

func (o *PersonData) GetData() PersonResource {
	if o == nil {
		return PersonResource{}
	}
	return o.Data
}
