// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

// PersonUpdateAttributes - A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
type PersonUpdateAttributes struct {
	// The two-letter abbreviation for the state in which the person resides, if located in the United States.  This is used for regulatory compliance purposes.
	//
	StateOfResidence string `json:"state_of_residence"`
}

func (o *PersonUpdateAttributes) GetStateOfResidence() string {
	if o == nil {
		return ""
	}
	return o.StateOfResidence
}

type PersonUpdateResource struct {
	type_ string `const:"people" json:"type"`
	ID    string `json:"id"`
	// A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
	PersonUpdateAttributes PersonUpdateAttributes `json:"attributes"`
}

func (p PersonUpdateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonUpdateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "id", "attributes"}); err != nil {
		return err
	}
	return nil
}

func (o *PersonUpdateResource) GetType() string {
	return "people"
}

func (o *PersonUpdateResource) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PersonUpdateResource) GetPersonUpdateAttributes() PersonUpdateAttributes {
	if o == nil {
		return PersonUpdateAttributes{}
	}
	return o.PersonUpdateAttributes
}

type PersonUpdateData struct {
	PersonUpdateResource PersonUpdateResource `json:"data"`
}

func (o *PersonUpdateData) GetPersonUpdateResource() PersonUpdateResource {
	if o == nil {
		return PersonUpdateResource{}
	}
	return o.PersonUpdateResource
}
