// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PersonLinks struct {
	// The URI for the user
	Self string `json:"self"`
}

func (o *PersonLinks) GetSelf() string {
	if o == nil {
		return ""
	}
	return o.Self
}
