// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	OauthClientCredentialsToken *SchemeOauthClientCredentialsToken `security:"scheme,type=oauth2,subtype=client_credentials"`
	OauthUserToken              *string                            `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetOauthClientCredentialsToken() *SchemeOauthClientCredentialsToken {
	if o == nil {
		return nil
	}
	return o.OauthClientCredentialsToken
}

func (o *Security) GetOauthUserToken() *string {
	if o == nil {
		return nil
	}
	return o.OauthUserToken
}
