// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type TransferCreateResource struct {
	type_ string `const:"transfers" json:"type"`
	// The unique identifier of the transfer. Any UUID version is valid, lower-cased.
	ID *string `json:"id,omitempty"`
	// An object representing a transfer of money from one account to another.
	// Created when a person takes an advance against a future paycheck, or on a daily basis
	// when we update estimated earnings based on current employment.
	//
	Attributes    TransferCreateAttributes    `json:"attributes"`
	Relationships TransferCreateRelationships `json:"relationships"`
}

func (t TransferCreateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferCreateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"type", "attributes", "relationships"}); err != nil {
		return err
	}
	return nil
}

func (o *TransferCreateResource) GetType() string {
	return "transfers"
}

func (o *TransferCreateResource) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TransferCreateResource) GetAttributes() TransferCreateAttributes {
	if o == nil {
		return TransferCreateAttributes{}
	}
	return o.Attributes
}

func (o *TransferCreateResource) GetRelationships() TransferCreateRelationships {
	if o == nil {
		return TransferCreateRelationships{}
	}
	return o.Relationships
}
