// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// TransferCreateAttributesSchedule - Set the schedule for the transfer. If not set, the transfer will be processed immediately.
// A preview transfer will never send.
type TransferCreateAttributesSchedule string

const (
	TransferCreateAttributesScheduleWithinThirtyMinutes TransferCreateAttributesSchedule = "WITHIN_THIRTY_MINUTES"
	TransferCreateAttributesScheduleNextBusinessDay     TransferCreateAttributesSchedule = "NEXT_BUSINESS_DAY"
)

func (e TransferCreateAttributesSchedule) ToPointer() *TransferCreateAttributesSchedule {
	return &e
}
func (e *TransferCreateAttributesSchedule) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "WITHIN_THIRTY_MINUTES":
		fallthrough
	case "NEXT_BUSINESS_DAY":
		*e = TransferCreateAttributesSchedule(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransferCreateAttributesSchedule: %v", v)
	}
}

// TransferCreateAttributes - An object representing a transfer of money from one account to another.
// Created when a person takes an advance against a future paycheck, or on a daily basis
// when we update estimated earnings based on current employment.
type TransferCreateAttributes struct {
	// Include this field to preview a transfer without sending it, to see, for example, the fee that would be charged. This will return the same response as a typical transfer request.
	// When the preview field is true in the response to creating a transfer, that indicates no transfer was created.
	//
	Preview *bool `default:"false" json:"preview"`
	// A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
	Amount int64 `json:"amount"`
	// A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
	Currency string `json:"currency"`
	// Set the schedule for the transfer. If not set, the transfer will be processed immediately.
	// A preview transfer will never send.
	//
	Schedule TransferCreateAttributesSchedule `json:"schedule"`
}

func (t TransferCreateAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferCreateAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"amount", "currency", "schedule"}); err != nil {
		return err
	}
	return nil
}

func (o *TransferCreateAttributes) GetPreview() *bool {
	if o == nil {
		return nil
	}
	return o.Preview
}

func (o *TransferCreateAttributes) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *TransferCreateAttributes) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *TransferCreateAttributes) GetSchedule() TransferCreateAttributesSchedule {
	if o == nil {
		return TransferCreateAttributesSchedule("")
	}
	return o.Schedule
}
