// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferLinks struct {
	Self string `json:"self"`
}

func (o *TransferLinks) GetSelf() string {
	if o == nil {
		return ""
	}
	return o.Self
}
