/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PersonRelationship,
  PersonRelationship$inboundSchema,
  PersonRelationship$Outbound,
  PersonRelationship$outboundSchema,
} from "./personrelationship.js";

export type AccountRelationships = {
  person: PersonRelationship;
};

/** @internal */
export const AccountRelationships$inboundSchema: z.ZodType<
  AccountRelationships,
  z.ZodTypeDef,
  unknown
> = z.object({
  person: PersonRelationship$inboundSchema,
});
/** @internal */
export type AccountRelationships$Outbound = {
  person: PersonRelationship$Outbound;
};

/** @internal */
export const AccountRelationships$outboundSchema: z.ZodType<
  AccountRelationships$Outbound,
  z.ZodTypeDef,
  AccountRelationships
> = z.object({
  person: PersonRelationship$outboundSchema,
});

export function accountRelationshipsToJSON(
  accountRelationships: AccountRelationships,
): string {
  return JSON.stringify(
    AccountRelationships$outboundSchema.parse(accountRelationships),
  );
}
export function accountRelationshipsFromJSON(
  jsonString: string,
): SafeParseResult<AccountRelationships, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountRelationships$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountRelationships' from JSON`,
  );
}
