/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountAttributes,
  AccountAttributes$inboundSchema,
} from "./accountattributes.js";
import { AccountLinks, AccountLinks$inboundSchema } from "./accountlinks.js";
import {
  AccountRelationships,
  AccountRelationships$inboundSchema,
} from "./accountrelationships.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AccountResource = {
  /**
   * The unique identifier of the Account.
   */
  id: string;
  /**
   * The type of the resource. Always `accounts`.
   */
  type: "accounts";
  /**
   * The details of the account.
   */
  attributes: AccountAttributes;
  links: AccountLinks;
  relationships: AccountRelationships;
};

/** @internal */
export const AccountResource$inboundSchema: z.ZodType<
  AccountResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.literal("accounts"),
  attributes: AccountAttributes$inboundSchema,
  links: AccountLinks$inboundSchema,
  relationships: AccountRelationships$inboundSchema,
});

export function accountResourceFromJSON(
  jsonString: string,
): SafeParseResult<AccountResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountResource' from JSON`,
  );
}
