/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountIdentifier,
  AccountIdentifier$inboundSchema,
  AccountIdentifier$Outbound,
  AccountIdentifier$outboundSchema,
} from "./accountidentifier.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AccountRelationship = {
  data: AccountIdentifier;
};

/** @internal */
export const AccountRelationship$inboundSchema: z.ZodType<
  AccountRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: AccountIdentifier$inboundSchema,
});
/** @internal */
export type AccountRelationship$Outbound = {
  data: AccountIdentifier$Outbound;
};

/** @internal */
export const AccountRelationship$outboundSchema: z.ZodType<
  AccountRelationship$Outbound,
  z.ZodTypeDef,
  AccountRelationship
> = z.object({
  data: AccountIdentifier$outboundSchema,
});

export function accountRelationshipToJSON(
  accountRelationship: AccountRelationship,
): string {
  return JSON.stringify(
    AccountRelationship$outboundSchema.parse(accountRelationship),
  );
}
export function accountRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<AccountRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountRelationship' from JSON`,
  );
}
