/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountResource,
  AccountResource$inboundSchema,
} from "./accountresource.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Returns the account object.
 */
export type AccountData = {
  data: AccountResource;
};

/** @internal */
export const AccountData$inboundSchema: z.ZodType<
  AccountData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: AccountResource$inboundSchema,
});

export function accountDataFromJSON(
  jsonString: string,
): SafeParseResult<AccountData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountData' from JSON`,
  );
}
