/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * The subtype of the account.
 */
export const AccountCreateAttributesDepositorySubtype = {
  Savings: "SAVINGS",
  Checking: "CHECKING",
} as const;
/**
 * The subtype of the account.
 */
export type AccountCreateAttributesDepositorySubtype = ClosedEnum<
  typeof AccountCreateAttributesDepositorySubtype
>;

/**
 * The banking details of the account and account holder.
 */
export type AccountCreateAttributesDepositoryDepositoryAccountDetails = {
  /**
   * The first name of the account holder.
   */
  firstName: string;
  /**
   * The last name of the account holder.
   */
  lastName: string;
  /**
   * The routing number of the bank that holds this account. Responses from this API that return this number are masked to the last four digits.
   */
  routingNumber: string;
  /**
   * The account number. Responses from this API that return this number are masked to the last four digits.
   */
  accountNumber: string;
};

/**
 * An account with type `DEPOSITORY` and subtype `SAVINGS` or `CHECKING`.
 */
export type AccountCreateAttributesDepository = {
  /**
   * Display name for this account.
   */
  name: string;
  /**
   * The type of account. It differentiates between depository accounts (e.g. bank account), cards (e.g. debit) and earnings balance type of accounts (e.g. on demand pay).
   */
  accountType: "DEPOSITORY";
  /**
   * The subtype of the account.
   */
  subtype: AccountCreateAttributesDepositorySubtype;
  /**
   * The banking details of the account and account holder.
   */
  depositoryAccountDetails:
    AccountCreateAttributesDepositoryDepositoryAccountDetails;
};

/** @internal */
export const AccountCreateAttributesDepositorySubtype$outboundSchema:
  z.ZodNativeEnum<typeof AccountCreateAttributesDepositorySubtype> = z
    .nativeEnum(AccountCreateAttributesDepositorySubtype);

/** @internal */
export type AccountCreateAttributesDepositoryDepositoryAccountDetails$Outbound =
  {
    first_name: string;
    last_name: string;
    routing_number: string;
    account_number: string;
  };

/** @internal */
export const AccountCreateAttributesDepositoryDepositoryAccountDetails$outboundSchema:
  z.ZodType<
    AccountCreateAttributesDepositoryDepositoryAccountDetails$Outbound,
    z.ZodTypeDef,
    AccountCreateAttributesDepositoryDepositoryAccountDetails
  > = z.object({
    firstName: z.string(),
    lastName: z.string(),
    routingNumber: z.string(),
    accountNumber: z.string(),
  }).transform((v) => {
    return remap$(v, {
      firstName: "first_name",
      lastName: "last_name",
      routingNumber: "routing_number",
      accountNumber: "account_number",
    });
  });

export function accountCreateAttributesDepositoryDepositoryAccountDetailsToJSON(
  accountCreateAttributesDepositoryDepositoryAccountDetails:
    AccountCreateAttributesDepositoryDepositoryAccountDetails,
): string {
  return JSON.stringify(
    AccountCreateAttributesDepositoryDepositoryAccountDetails$outboundSchema
      .parse(accountCreateAttributesDepositoryDepositoryAccountDetails),
  );
}

/** @internal */
export type AccountCreateAttributesDepository$Outbound = {
  name: string;
  account_type: "DEPOSITORY";
  subtype: string;
  details: AccountCreateAttributesDepositoryDepositoryAccountDetails$Outbound;
};

/** @internal */
export const AccountCreateAttributesDepository$outboundSchema: z.ZodType<
  AccountCreateAttributesDepository$Outbound,
  z.ZodTypeDef,
  AccountCreateAttributesDepository
> = z.object({
  name: z.string(),
  accountType: z.literal("DEPOSITORY"),
  subtype: AccountCreateAttributesDepositorySubtype$outboundSchema,
  depositoryAccountDetails: z.lazy(() =>
    AccountCreateAttributesDepositoryDepositoryAccountDetails$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    accountType: "account_type",
    depositoryAccountDetails: "details",
  });
});

export function accountCreateAttributesDepositoryToJSON(
  accountCreateAttributesDepository: AccountCreateAttributesDepository,
): string {
  return JSON.stringify(
    AccountCreateAttributesDepository$outboundSchema.parse(
      accountCreateAttributesDepository,
    ),
  );
}
