/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A list of links to resources that may be helpful in resolving the error.
 */
export type ErrorAccountCreateErrorLinks = {
  about?: string | undefined;
};

/**
 * Location in the request that may have caused the error.
 */
export type ErrorAccountCreateErrorSource = {
  /**
   * The name of the parameter that caused the error.
   */
  parameter?: string | undefined;
  /**
   * A JSON Pointer to the location in the request that caused the error.
   */
  pointer?: string | undefined;
  /**
   * The name of the header that caused the error.
   */
  header?: string | undefined;
};

/**
 * Additional information about the error.
 */
export type ErrorAccountCreateErrorMeta = {
  /**
   * A UUID for the originating request.
   */
  requestId?: string | undefined;
  /**
   * An ID used for tracing purposes.
   */
  traceId?: string | undefined;
};

export type ErrorAccountCreateError = {
  /**
   * A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
   */
  code: string;
  /**
   * The HTTP status code for the error.
   */
  status: string;
  /**
   * A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
   */
  detail: string;
  /**
   * A list of links to resources that may be helpful in resolving the error.
   */
  links: ErrorAccountCreateErrorLinks;
  /**
   * Location in the request that may have caused the error.
   */
  source?: ErrorAccountCreateErrorSource | undefined;
  /**
   * Additional information about the error.
   */
  meta: ErrorAccountCreateErrorMeta;
};

/** @internal */
export const ErrorAccountCreateErrorLinks$inboundSchema: z.ZodType<
  ErrorAccountCreateErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  about: z.string().optional(),
});

export function errorAccountCreateErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<ErrorAccountCreateErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorAccountCreateErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorAccountCreateErrorLinks' from JSON`,
  );
}

/** @internal */
export const ErrorAccountCreateErrorSource$inboundSchema: z.ZodType<
  ErrorAccountCreateErrorSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameter: z.string().optional(),
  pointer: z.string().optional(),
  header: z.string().optional(),
});

export function errorAccountCreateErrorSourceFromJSON(
  jsonString: string,
): SafeParseResult<ErrorAccountCreateErrorSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorAccountCreateErrorSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorAccountCreateErrorSource' from JSON`,
  );
}

/** @internal */
export const ErrorAccountCreateErrorMeta$inboundSchema: z.ZodType<
  ErrorAccountCreateErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  trace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "trace_id": "traceId",
  });
});

export function errorAccountCreateErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorAccountCreateErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorAccountCreateErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorAccountCreateErrorMeta' from JSON`,
  );
}

/** @internal */
export const ErrorAccountCreateError$inboundSchema: z.ZodType<
  ErrorAccountCreateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  status: z.string(),
  detail: z.string(),
  links: z.lazy(() => ErrorAccountCreateErrorLinks$inboundSchema),
  source: z.lazy(() => ErrorAccountCreateErrorSource$inboundSchema).optional(),
  meta: z.lazy(() => ErrorAccountCreateErrorMeta$inboundSchema),
});

export function errorAccountCreateErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorAccountCreateError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorAccountCreateError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorAccountCreateError' from JSON`,
  );
}
