/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A list of links to resources that may be helpful in resolving the error.
 */
export type ErrorNotFoundErrorLinks = {
  about?: string | undefined;
};

/**
 * Location in the request that may have caused the error.
 */
export type ErrorNotFoundErrorSource = {
  /**
   * The name of the parameter that caused the error.
   */
  parameter?: string | undefined;
  /**
   * A JSON Pointer to the location in the request that caused the error.
   */
  pointer?: string | undefined;
  /**
   * The name of the header that caused the error.
   */
  header?: string | undefined;
};

/**
 * Additional information about the error.
 */
export type ErrorNotFoundErrorMeta = {
  /**
   * A UUID for the originating request.
   */
  requestId?: string | undefined;
  /**
   * An ID used for tracing purposes.
   */
  traceId?: string | undefined;
};

/**
 * A code that indicates what went wrong.
 */
export const ErrorNotFoundErrorCode = {
  RecordNotFound: "RECORD_NOT_FOUND",
  NotFound: "NOT_FOUND",
} as const;
/**
 * A code that indicates what went wrong.
 */
export type ErrorNotFoundErrorCode = ClosedEnum<typeof ErrorNotFoundErrorCode>;

export type ErrorNotFoundError = {
  /**
   * The HTTP status code for the error.
   */
  status: string;
  /**
   * A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
   */
  detail: string;
  /**
   * A list of links to resources that may be helpful in resolving the error.
   */
  links: ErrorNotFoundErrorLinks;
  /**
   * Location in the request that may have caused the error.
   */
  source?: ErrorNotFoundErrorSource | undefined;
  /**
   * Additional information about the error.
   */
  meta: ErrorNotFoundErrorMeta;
  /**
   * A code that indicates what went wrong.
   */
  code: ErrorNotFoundErrorCode;
};

/** @internal */
export const ErrorNotFoundErrorLinks$inboundSchema: z.ZodType<
  ErrorNotFoundErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  about: z.string().optional(),
});

export function errorNotFoundErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<ErrorNotFoundErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorNotFoundErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorNotFoundErrorLinks' from JSON`,
  );
}

/** @internal */
export const ErrorNotFoundErrorSource$inboundSchema: z.ZodType<
  ErrorNotFoundErrorSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameter: z.string().optional(),
  pointer: z.string().optional(),
  header: z.string().optional(),
});

export function errorNotFoundErrorSourceFromJSON(
  jsonString: string,
): SafeParseResult<ErrorNotFoundErrorSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorNotFoundErrorSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorNotFoundErrorSource' from JSON`,
  );
}

/** @internal */
export const ErrorNotFoundErrorMeta$inboundSchema: z.ZodType<
  ErrorNotFoundErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  trace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "trace_id": "traceId",
  });
});

export function errorNotFoundErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorNotFoundErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorNotFoundErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorNotFoundErrorMeta' from JSON`,
  );
}

/** @internal */
export const ErrorNotFoundErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof ErrorNotFoundErrorCode
> = z.nativeEnum(ErrorNotFoundErrorCode);

/** @internal */
export const ErrorNotFoundError$inboundSchema: z.ZodType<
  ErrorNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  detail: z.string(),
  links: z.lazy(() => ErrorNotFoundErrorLinks$inboundSchema),
  source: z.lazy(() => ErrorNotFoundErrorSource$inboundSchema).optional(),
  meta: z.lazy(() => ErrorNotFoundErrorMeta$inboundSchema),
  code: ErrorNotFoundErrorCode$inboundSchema,
});

export function errorNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorNotFoundError' from JSON`,
  );
}
