/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A list of links to resources that may be helpful in resolving the error.
 */
export type ErrorTransferCreateErrorLinks = {
  about?: string | undefined;
};

/**
 * Location in the request that may have caused the error.
 */
export type ErrorTransferCreateErrorSource = {
  /**
   * The name of the parameter that caused the error.
   */
  parameter?: string | undefined;
  /**
   * A JSON Pointer to the location in the request that caused the error.
   */
  pointer?: string | undefined;
  /**
   * The name of the header that caused the error.
   */
  header?: string | undefined;
};

/**
 * Additional information about the error.
 */
export type ErrorTransferCreateErrorMeta = {
  /**
   * A UUID for the originating request.
   */
  requestId?: string | undefined;
  /**
   * An ID used for tracing purposes.
   */
  traceId?: string | undefined;
};

export type ErrorTransferCreateError = {
  /**
   * A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
   */
  code: string;
  /**
   * The HTTP status code for the error.
   */
  status: string;
  /**
   * A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
   */
  detail: string;
  /**
   * A list of links to resources that may be helpful in resolving the error.
   */
  links: ErrorTransferCreateErrorLinks;
  /**
   * Location in the request that may have caused the error.
   */
  source?: ErrorTransferCreateErrorSource | undefined;
  /**
   * Additional information about the error.
   */
  meta: ErrorTransferCreateErrorMeta;
};

/** @internal */
export const ErrorTransferCreateErrorLinks$inboundSchema: z.ZodType<
  ErrorTransferCreateErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  about: z.string().optional(),
});

export function errorTransferCreateErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTransferCreateErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTransferCreateErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTransferCreateErrorLinks' from JSON`,
  );
}

/** @internal */
export const ErrorTransferCreateErrorSource$inboundSchema: z.ZodType<
  ErrorTransferCreateErrorSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameter: z.string().optional(),
  pointer: z.string().optional(),
  header: z.string().optional(),
});

export function errorTransferCreateErrorSourceFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTransferCreateErrorSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTransferCreateErrorSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTransferCreateErrorSource' from JSON`,
  );
}

/** @internal */
export const ErrorTransferCreateErrorMeta$inboundSchema: z.ZodType<
  ErrorTransferCreateErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  trace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "trace_id": "traceId",
  });
});

export function errorTransferCreateErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTransferCreateErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTransferCreateErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTransferCreateErrorMeta' from JSON`,
  );
}

/** @internal */
export const ErrorTransferCreateError$inboundSchema: z.ZodType<
  ErrorTransferCreateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  status: z.string(),
  detail: z.string(),
  links: z.lazy(() => ErrorTransferCreateErrorLinks$inboundSchema),
  source: z.lazy(() => ErrorTransferCreateErrorSource$inboundSchema).optional(),
  meta: z.lazy(() => ErrorTransferCreateErrorMeta$inboundSchema),
});

export function errorTransferCreateErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTransferCreateError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTransferCreateError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTransferCreateError' from JSON`,
  );
}
