/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A list of links to resources that may be helpful in resolving the error.
 */
export type ErrorForbiddenErrorLinks = {
  about?: string | undefined;
};

/**
 * Location in the request that may have caused the error.
 */
export type ErrorForbiddenErrorSource = {
  /**
   * The name of the parameter that caused the error.
   */
  parameter?: string | undefined;
  /**
   * A JSON Pointer to the location in the request that caused the error.
   */
  pointer?: string | undefined;
  /**
   * The name of the header that caused the error.
   */
  header?: string | undefined;
};

/**
 * Additional information about the error.
 */
export type ErrorForbiddenErrorMeta = {
  /**
   * A UUID for the originating request.
   */
  requestId?: string | undefined;
  /**
   * An ID used for tracing purposes.
   */
  traceId?: string | undefined;
};

/**
 * A code that indicates what went wrong.
 */
export const ErrorForbiddenErrorCode = {
  Forbidden: "FORBIDDEN",
} as const;
/**
 * A code that indicates what went wrong.
 */
export type ErrorForbiddenErrorCode = ClosedEnum<
  typeof ErrorForbiddenErrorCode
>;

export type ErrorForbiddenError = {
  /**
   * The HTTP status code for the error.
   */
  status: string;
  /**
   * A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
   */
  detail: string;
  /**
   * A list of links to resources that may be helpful in resolving the error.
   */
  links: ErrorForbiddenErrorLinks;
  /**
   * Location in the request that may have caused the error.
   */
  source?: ErrorForbiddenErrorSource | undefined;
  /**
   * Additional information about the error.
   */
  meta: ErrorForbiddenErrorMeta;
  /**
   * A code that indicates what went wrong.
   */
  code: ErrorForbiddenErrorCode;
};

/** @internal */
export const ErrorForbiddenErrorLinks$inboundSchema: z.ZodType<
  ErrorForbiddenErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  about: z.string().optional(),
});

export function errorForbiddenErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<ErrorForbiddenErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorForbiddenErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorForbiddenErrorLinks' from JSON`,
  );
}

/** @internal */
export const ErrorForbiddenErrorSource$inboundSchema: z.ZodType<
  ErrorForbiddenErrorSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameter: z.string().optional(),
  pointer: z.string().optional(),
  header: z.string().optional(),
});

export function errorForbiddenErrorSourceFromJSON(
  jsonString: string,
): SafeParseResult<ErrorForbiddenErrorSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorForbiddenErrorSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorForbiddenErrorSource' from JSON`,
  );
}

/** @internal */
export const ErrorForbiddenErrorMeta$inboundSchema: z.ZodType<
  ErrorForbiddenErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  trace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "trace_id": "traceId",
  });
});

export function errorForbiddenErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorForbiddenErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorForbiddenErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorForbiddenErrorMeta' from JSON`,
  );
}

/** @internal */
export const ErrorForbiddenErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof ErrorForbiddenErrorCode
> = z.nativeEnum(ErrorForbiddenErrorCode);

/** @internal */
export const ErrorForbiddenError$inboundSchema: z.ZodType<
  ErrorForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  detail: z.string(),
  links: z.lazy(() => ErrorForbiddenErrorLinks$inboundSchema),
  source: z.lazy(() => ErrorForbiddenErrorSource$inboundSchema).optional(),
  meta: z.lazy(() => ErrorForbiddenErrorMeta$inboundSchema),
  code: ErrorForbiddenErrorCode$inboundSchema,
});

export function errorForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorForbiddenError' from JSON`,
  );
}
