/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A list of links to resources that may be helpful in resolving the error.
 */
export type ErrorJobUpdateErrorLinks = {
  about?: string | undefined;
};

/**
 * Location in the request that may have caused the error.
 */
export type ErrorJobUpdateErrorSource = {
  /**
   * The name of the parameter that caused the error.
   */
  parameter?: string | undefined;
  /**
   * A JSON Pointer to the location in the request that caused the error.
   */
  pointer?: string | undefined;
  /**
   * The name of the header that caused the error.
   */
  header?: string | undefined;
};

/**
 * Additional information about the error.
 */
export type ErrorJobUpdateErrorMeta = {
  /**
   * A UUID for the originating request.
   */
  requestId?: string | undefined;
  /**
   * An ID used for tracing purposes.
   */
  traceId?: string | undefined;
};

export type ErrorJobUpdateError = {
  /**
   * A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
   */
  code: string;
  /**
   * The HTTP status code for the error.
   */
  status: string;
  /**
   * A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
   */
  detail: string;
  /**
   * A list of links to resources that may be helpful in resolving the error.
   */
  links: ErrorJobUpdateErrorLinks;
  /**
   * Location in the request that may have caused the error.
   */
  source?: ErrorJobUpdateErrorSource | undefined;
  /**
   * Additional information about the error.
   */
  meta: ErrorJobUpdateErrorMeta;
};

/** @internal */
export const ErrorJobUpdateErrorLinks$inboundSchema: z.ZodType<
  ErrorJobUpdateErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  about: z.string().optional(),
});

export function errorJobUpdateErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<ErrorJobUpdateErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorJobUpdateErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorJobUpdateErrorLinks' from JSON`,
  );
}

/** @internal */
export const ErrorJobUpdateErrorSource$inboundSchema: z.ZodType<
  ErrorJobUpdateErrorSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameter: z.string().optional(),
  pointer: z.string().optional(),
  header: z.string().optional(),
});

export function errorJobUpdateErrorSourceFromJSON(
  jsonString: string,
): SafeParseResult<ErrorJobUpdateErrorSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorJobUpdateErrorSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorJobUpdateErrorSource' from JSON`,
  );
}

/** @internal */
export const ErrorJobUpdateErrorMeta$inboundSchema: z.ZodType<
  ErrorJobUpdateErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  trace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "trace_id": "traceId",
  });
});

export function errorJobUpdateErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorJobUpdateErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorJobUpdateErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorJobUpdateErrorMeta' from JSON`,
  );
}

/** @internal */
export const ErrorJobUpdateError$inboundSchema: z.ZodType<
  ErrorJobUpdateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  status: z.string(),
  detail: z.string(),
  links: z.lazy(() => ErrorJobUpdateErrorLinks$inboundSchema),
  source: z.lazy(() => ErrorJobUpdateErrorSource$inboundSchema).optional(),
  meta: z.lazy(() => ErrorJobUpdateErrorMeta$inboundSchema),
});

export function errorJobUpdateErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorJobUpdateError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorJobUpdateError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorJobUpdateError' from JSON`,
  );
}
