/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const FilterPaycheckStatus = {
  Estimated: "ESTIMATED",
  Processing: "PROCESSING",
  InTransit: "IN_TRANSIT",
  Deposited: "DEPOSITED",
} as const;
export type FilterPaycheckStatus = ClosedEnum<typeof FilterPaycheckStatus>;

/** @internal */
export const FilterPaycheckStatus$outboundSchema: z.ZodNativeEnum<
  typeof FilterPaycheckStatus
> = z.nativeEnum(FilterPaycheckStatus);
