/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const FilterAccountType = {
  EarningsBalance: "EARNINGS_BALANCE",
  Depository: "DEPOSITORY",
  Card: "CARD",
} as const;
export type FilterAccountType = ClosedEnum<typeof FilterAccountType>;

/** @internal */
export const FilterAccountType$outboundSchema: z.ZodNativeEnum<
  typeof FilterAccountType
> = z.nativeEnum(FilterAccountType);
