/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FundingSourceAttributes,
  FundingSourceAttributes$inboundSchema,
} from "./fundingsourceattributes.js";
import {
  FundingSourceRelationships,
  FundingSourceRelationships$inboundSchema,
} from "./fundingsourcerelationships.js";

/**
 * A source describes how transfers with an origin of EARNINGS_BALANCE account are funded.
 */
export type FundingSourceResource = {
  id: string;
  type: "funding_sources";
  attributes: FundingSourceAttributes;
  relationships: FundingSourceRelationships;
};

/** @internal */
export const FundingSourceResource$inboundSchema: z.ZodType<
  FundingSourceResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.literal("funding_sources"),
  attributes: FundingSourceAttributes$inboundSchema,
  relationships: FundingSourceRelationships$inboundSchema,
});

export function fundingSourceResourceFromJSON(
  jsonString: string,
): SafeParseResult<FundingSourceResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FundingSourceResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FundingSourceResource' from JSON`,
  );
}
