/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Activation is the process of verifying that data is available for a Job,  and that a person has verified their identity as the Person associated with the Job. Only paychecks from Jobs with `activated` status will contribute to an earnings balance account.
 *
 * @remarks
 *
 * To deactivate a job, update activation_status to `DEACTIVATED`.
 */
export const JobAttributesActivationStatus = {
  Deactivated: "DEACTIVATED",
  DeactivationPending: "DEACTIVATION_PENDING",
  ActivationRequired: "ACTIVATION_REQUIRED",
  ActivationUnderReview: "ACTIVATION_UNDER_REVIEW",
  Activated: "ACTIVATED",
} as const;
/**
 * Activation is the process of verifying that data is available for a Job,  and that a person has verified their identity as the Person associated with the Job. Only paychecks from Jobs with `activated` status will contribute to an earnings balance account.
 *
 * @remarks
 *
 * To deactivate a job, update activation_status to `DEACTIVATED`.
 */
export type JobAttributesActivationStatus = ClosedEnum<
  typeof JobAttributesActivationStatus
>;

export const Frequency = {
  Hourly: "HOURLY",
  Weekly: "WEEKLY",
  Biweekly: "BIWEEKLY",
  TwiceMonthly: "TWICE_MONTHLY",
  Monthly: "MONTHLY",
  Annually: "ANNUALLY",
} as const;
export type Frequency = ClosedEnum<typeof Frequency>;

export type WageRate = {
  /**
   * A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
   */
  amount: number;
  /**
   * A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
   */
  currency: string;
  frequency: Frequency;
};

/**
 * - `SETUP_REQUIRED` Direct deposit is not set up for this Job. Update this resource's relationships to set up direct deposit.
 *
 * @remarks
 * - `SETUP_PENDING` A system action is still pending.
 * - `SETUP_COMPLETE` Direct deposit is set up for this Job.
 */
export const DirectDepositStatus = {
  SetupRequired: "SETUP_REQUIRED",
  SetupPending: "SETUP_PENDING",
  SetupComplete: "SETUP_COMPLETE",
} as const;
/**
 * - `SETUP_REQUIRED` Direct deposit is not set up for this Job. Update this resource's relationships to set up direct deposit.
 *
 * @remarks
 * - `SETUP_PENDING` A system action is still pending.
 * - `SETUP_COMPLETE` Direct deposit is set up for this Job.
 */
export type DirectDepositStatus = ClosedEnum<typeof DirectDepositStatus>;

export type JobAttributes = {
  /**
   * Holds unique identifiers for the employee or job defined by external organizations.
   */
  externalIdentifiers?: { [k: string]: string } | undefined;
  /**
   * The first name of the person as it is listed in their employee profile.
   */
  firstName?: string | undefined;
  /**
   * The last name of the person as it is listed in their employee profile.
   */
  lastName?: string | undefined;
  /**
   * Activation is the process of verifying that data is available for a Job,  and that a person has verified their identity as the Person associated with the Job. Only paychecks from Jobs with `activated` status will contribute to an earnings balance account.
   *
   * @remarks
   *
   * To deactivate a job, update activation_status to `DEACTIVATED`.
   */
  activationStatus: JobAttributesActivationStatus;
  wageRate: WageRate;
  title?: string | null | undefined;
  department?: string | null | undefined;
  location?: string | undefined;
  /**
   * - `SETUP_REQUIRED` Direct deposit is not set up for this Job. Update this resource's relationships to set up direct deposit.
   *
   * @remarks
   * - `SETUP_PENDING` A system action is still pending.
   * - `SETUP_COMPLETE` Direct deposit is set up for this Job.
   */
  directDepositStatus: DirectDepositStatus;
};

/** @internal */
export const JobAttributesActivationStatus$inboundSchema: z.ZodNativeEnum<
  typeof JobAttributesActivationStatus
> = z.nativeEnum(JobAttributesActivationStatus);

/** @internal */
export const Frequency$inboundSchema: z.ZodNativeEnum<typeof Frequency> = z
  .nativeEnum(Frequency);

/** @internal */
export const WageRate$inboundSchema: z.ZodType<
  WageRate,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int(),
  currency: z.string(),
  frequency: Frequency$inboundSchema,
});

export function wageRateFromJSON(
  jsonString: string,
): SafeParseResult<WageRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WageRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WageRate' from JSON`,
  );
}

/** @internal */
export const DirectDepositStatus$inboundSchema: z.ZodNativeEnum<
  typeof DirectDepositStatus
> = z.nativeEnum(DirectDepositStatus);

/** @internal */
export const JobAttributes$inboundSchema: z.ZodType<
  JobAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_identifiers: z.record(z.string()).optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  activation_status: JobAttributesActivationStatus$inboundSchema,
  wage_rate: z.lazy(() => WageRate$inboundSchema),
  title: z.nullable(z.string()).optional(),
  department: z.nullable(z.string()).optional(),
  location: z.string().optional(),
  direct_deposit_status: DirectDepositStatus$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "external_identifiers": "externalIdentifiers",
    "first_name": "firstName",
    "last_name": "lastName",
    "activation_status": "activationStatus",
    "wage_rate": "wageRate",
    "direct_deposit_status": "directDepositStatus",
  });
});

export function jobAttributesFromJSON(
  jsonString: string,
): SafeParseResult<JobAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobAttributes' from JSON`,
  );
}
