/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { JobResource, JobResource$inboundSchema } from "./jobresource.js";

/**
 * Returns the job object.
 */
export type JobData = {
  /**
   * A job describes the financial relationship between a person and an organization.
   */
  data: JobResource;
};

/** @internal */
export const JobData$inboundSchema: z.ZodType<JobData, z.ZodTypeDef, unknown> =
  z.object({
    data: JobResource$inboundSchema,
  });

export function jobDataFromJSON(
  jsonString: string,
): SafeParseResult<JobData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobData' from JSON`,
  );
}
