/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type JobLinks = {
  self: string;
};

/** @internal */
export const JobLinks$inboundSchema: z.ZodType<
  JobLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string(),
});

export function jobLinksFromJSON(
  jsonString: string,
): SafeParseResult<JobLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobLinks' from JSON`,
  );
}
