/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { JobAttributes, JobAttributes$inboundSchema } from "./jobattributes.js";
import { JobLinks, JobLinks$inboundSchema } from "./joblinks.js";
import {
  JobRelationships,
  JobRelationships$inboundSchema,
} from "./jobrelationships.js";

/**
 * A job describes the financial relationship between a person and an organization.
 */
export type JobResource = {
  type: "jobs";
  id: string;
  attributes: JobAttributes;
  links: JobLinks;
  /**
   * The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
   */
  relationships: JobRelationships;
};

/** @internal */
export const JobResource$inboundSchema: z.ZodType<
  JobResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("jobs"),
  id: z.string(),
  attributes: JobAttributes$inboundSchema,
  links: JobLinks$inboundSchema,
  relationships: JobRelationships$inboundSchema,
});

export function jobResourceFromJSON(
  jsonString: string,
): SafeParseResult<JobResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobResource' from JSON`,
  );
}
