/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { JobIdentifier, JobIdentifier$inboundSchema } from "./jobidentifier.js";

export type JobRelationship = {
  data: JobIdentifier;
};

/** @internal */
export const JobRelationship$inboundSchema: z.ZodType<
  JobRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: JobIdentifier$inboundSchema,
});

export function jobRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<JobRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobRelationship' from JSON`,
  );
}
