/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountRelationship,
  AccountRelationship$inboundSchema,
} from "./accountrelationship.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrganizationRelationship,
  OrganizationRelationship$inboundSchema,
} from "./organizationrelationship.js";
import {
  PersonRelationship,
  PersonRelationship$inboundSchema,
} from "./personrelationship.js";

/**
 * The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
 */
export type JobRelationships = {
  person: PersonRelationship;
  organization: OrganizationRelationship;
  directDepositDefaultDepository?: AccountRelationship | undefined;
  directDepositDefaultCard?: AccountRelationship | undefined;
};

/** @internal */
export const JobRelationships$inboundSchema: z.ZodType<
  JobRelationships,
  z.ZodTypeDef,
  unknown
> = z.object({
  person: PersonRelationship$inboundSchema,
  organization: OrganizationRelationship$inboundSchema,
  direct_deposit_default_depository: AccountRelationship$inboundSchema
    .optional(),
  direct_deposit_default_card: AccountRelationship$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "direct_deposit_default_depository": "directDepositDefaultDepository",
    "direct_deposit_default_card": "directDepositDefaultCard",
  });
});

export function jobRelationshipsFromJSON(
  jsonString: string,
): SafeParseResult<JobRelationships, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobRelationships$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobRelationships' from JSON`,
  );
}
