/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { JobResource, JobResource$inboundSchema } from "./jobresource.js";

/**
 * Returns a list of job objects.
 */
export type JobsData = {
  data: Array<JobResource>;
};

/** @internal */
export const JobsData$inboundSchema: z.ZodType<
  JobsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(JobResource$inboundSchema),
});

export function jobsDataFromJSON(
  jsonString: string,
): SafeParseResult<JobsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobsData' from JSON`,
  );
}
