/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OrganizationAttributes = {
  /**
   * Organization's name
   */
  name?: string | undefined;
  /**
   * List of the names of products available for this organization.
   */
  products?: Array<string> | undefined;
};

/** @internal */
export const OrganizationAttributes$inboundSchema: z.ZodType<
  OrganizationAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  products: z.array(z.string()).optional(),
});

export function organizationAttributesFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationAttributes' from JSON`,
  );
}
