/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrganizationResource,
  OrganizationResource$inboundSchema,
} from "./organizationresource.js";

/**
 * Returns a list of organization objects that match the filter. If no organizations match the filter, the resulting collection will be empty. If no filter is provider, the resulting collection will include all accessible organizations.
 */
export type OrganizationsData = {
  data: Array<OrganizationResource>;
};

/** @internal */
export const OrganizationsData$inboundSchema: z.ZodType<
  OrganizationsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(OrganizationResource$inboundSchema),
});

export function organizationsDataFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationsData' from JSON`,
  );
}
