/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OrganizationLinks = {
  self: string;
};

/** @internal */
export const OrganizationLinks$inboundSchema: z.ZodType<
  OrganizationLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string(),
});

export function organizationLinksFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationLinks' from JSON`,
  );
}
