/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OrganizationIdentifier = {
  type: "organizations";
  id: string;
};

/** @internal */
export const OrganizationIdentifier$inboundSchema: z.ZodType<
  OrganizationIdentifier,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("organizations"),
  id: z.string(),
});

export function organizationIdentifierFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationIdentifier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationIdentifier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationIdentifier' from JSON`,
  );
}
