/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrganizationIdentifier,
  OrganizationIdentifier$inboundSchema,
} from "./organizationidentifier.js";

export type OrganizationRelationship = {
  data: OrganizationIdentifier;
};

/** @internal */
export const OrganizationRelationship$inboundSchema: z.ZodType<
  OrganizationRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: OrganizationIdentifier$inboundSchema,
});

export function organizationRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationRelationship' from JSON`,
  );
}
