/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrganizationAttributes,
  OrganizationAttributes$inboundSchema,
} from "./organizationattributes.js";
import {
  OrganizationLinks,
  OrganizationLinks$inboundSchema,
} from "./organizationlinks.js";

export type OrganizationResource = {
  type: "organizations";
  /**
   * String identifier that is unique to this organization. You can safely assume the identifier to never exceed 64 characters.
   */
  id: string;
  attributes: OrganizationAttributes;
  links: OrganizationLinks;
};

/** @internal */
export const OrganizationResource$inboundSchema: z.ZodType<
  OrganizationResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("organizations"),
  id: z.string(),
  attributes: OrganizationAttributes$inboundSchema,
  links: OrganizationLinks$inboundSchema,
});

export function organizationResourceFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationResource' from JSON`,
  );
}
