/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaycheckIdentifier,
  PaycheckIdentifier$inboundSchema,
} from "./paycheckidentifier.js";

export type PaycheckRelationship = {
  data: PaycheckIdentifier;
};

/** @internal */
export const PaycheckRelationship$inboundSchema: z.ZodType<
  PaycheckRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: PaycheckIdentifier$inboundSchema,
});

export function paycheckRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<PaycheckRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaycheckRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaycheckRelationship' from JSON`,
  );
}
