/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PaycheckIdentifier = {
  type: "paychecks";
  id: string;
};

/** @internal */
export const PaycheckIdentifier$inboundSchema: z.ZodType<
  PaycheckIdentifier,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("paychecks"),
  id: z.string(),
});

export function paycheckIdentifierFromJSON(
  jsonString: string,
): SafeParseResult<PaycheckIdentifier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaycheckIdentifier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaycheckIdentifier' from JSON`,
  );
}
