/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PaycheckLinks = {
  self: string;
};

/** @internal */
export const PaycheckLinks$inboundSchema: z.ZodType<
  PaycheckLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string(),
});

export function paycheckLinksFromJSON(
  jsonString: string,
): SafeParseResult<PaycheckLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaycheckLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaycheckLinks' from JSON`,
  );
}
