/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  JobRelationship,
  JobRelationship$inboundSchema,
} from "./jobrelationship.js";
import {
  PersonRelationship,
  PersonRelationship$inboundSchema,
} from "./personrelationship.js";

export type PaycheckRelationships = {
  person: PersonRelationship;
  job: JobRelationship;
};

/** @internal */
export const PaycheckRelationships$inboundSchema: z.ZodType<
  PaycheckRelationships,
  z.ZodTypeDef,
  unknown
> = z.object({
  person: PersonRelationship$inboundSchema,
  job: JobRelationship$inboundSchema,
});

export function paycheckRelationshipsFromJSON(
  jsonString: string,
): SafeParseResult<PaycheckRelationships, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaycheckRelationships$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaycheckRelationships' from JSON`,
  );
}
