/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaycheckResource,
  PaycheckResource$inboundSchema,
} from "./paycheckresource.js";

/**
 * Returns the paycheck object.
 */
export type PaycheckData = {
  data: PaycheckResource;
};

/** @internal */
export const PaycheckData$inboundSchema: z.ZodType<
  PaycheckData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: PaycheckResource$inboundSchema,
});

export function paycheckDataFromJSON(
  jsonString: string,
): SafeParseResult<PaycheckData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaycheckData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaycheckData' from JSON`,
  );
}
