/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaycheckResource,
  PaycheckResource$inboundSchema,
} from "./paycheckresource.js";

/**
 * Returns the paycheck object.
 */
export type PaychecksData = {
  data: Array<PaycheckResource>;
};

/** @internal */
export const PaychecksData$inboundSchema: z.ZodType<
  PaychecksData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(PaycheckResource$inboundSchema),
});

export function paychecksDataFromJSON(
  jsonString: string,
): SafeParseResult<PaychecksData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaychecksData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaychecksData' from JSON`,
  );
}
