/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PersonIdentifier,
  PersonIdentifier$inboundSchema,
  PersonIdentifier$Outbound,
  PersonIdentifier$outboundSchema,
} from "./personidentifier.js";

export type PersonRelationship = {
  data: PersonIdentifier;
};

/** @internal */
export const PersonRelationship$inboundSchema: z.ZodType<
  PersonRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: PersonIdentifier$inboundSchema,
});
/** @internal */
export type PersonRelationship$Outbound = {
  data: PersonIdentifier$Outbound;
};

/** @internal */
export const PersonRelationship$outboundSchema: z.ZodType<
  PersonRelationship$Outbound,
  z.ZodTypeDef,
  PersonRelationship
> = z.object({
  data: PersonIdentifier$outboundSchema,
});

export function personRelationshipToJSON(
  personRelationship: PersonRelationship,
): string {
  return JSON.stringify(
    PersonRelationship$outboundSchema.parse(personRelationship),
  );
}
export function personRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<PersonRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PersonRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersonRelationship' from JSON`,
  );
}
