/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PersonAttributes,
  PersonAttributes$inboundSchema,
} from "./personattributes.js";
import { PersonLinks, PersonLinks$inboundSchema } from "./personlinks.js";

export type PersonResource = {
  type: "people";
  id: string;
  /**
   * A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
   */
  attributes: PersonAttributes;
  links: PersonLinks;
};

/** @internal */
export const PersonResource$inboundSchema: z.ZodType<
  PersonResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("people"),
  id: z.string(),
  attributes: PersonAttributes$inboundSchema,
  links: PersonLinks$inboundSchema,
});

export function personResourceFromJSON(
  jsonString: string,
): SafeParseResult<PersonResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PersonResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersonResource' from JSON`,
  );
}
