/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The statuses and required actions are:
 *
 * @remarks
 * - `null` The person has not been disallowed, and is free to use DailyPay.
 * - `INACTIVE` The person has not completed registration or account verification.
 * - `DELINQUENT` The person has an outstanding, unrecoverable balance with DailyPay, and should contact support.
 * - `BANNED` Access has been revoked.
 */
export const DisallowReason = {
  Inactive: "INACTIVE",
  Delinquent: "DELINQUENT",
  Banned: "BANNED",
} as const;
/**
 * The statuses and required actions are:
 *
 * @remarks
 * - `null` The person has not been disallowed, and is free to use DailyPay.
 * - `INACTIVE` The person has not completed registration or account verification.
 * - `DELINQUENT` The person has an outstanding, unrecoverable balance with DailyPay, and should contact support.
 * - `BANNED` Access has been revoked.
 */
export type DisallowReason = ClosedEnum<typeof DisallowReason>;

/**
 * The DailyPay Visa®️ Prepaid Card program. A person can be either eligible or enrolled, but not both.
 *
 * @remarks
 */
export type DailyPayCardProductEntitlement = {
  /**
   * Whether the person is eligible to enroll in the DailyPay Visa®️ Prepaid Card program.
   *
   * @remarks
   */
  eligible: boolean;
  /**
   * Whether the person is enrolled in the DailyPay Visa®️ Prepaid Card program.
   *
   * @remarks
   */
  enrolled: boolean;
};

/**
 * Products that the person is enrolled in or eligible for. This data is refreshed nightly.
 *
 * @remarks
 */
export type Products = {
  /**
   * The DailyPay Visa®️ Prepaid Card program. A person can be either eligible or enrolled, but not both.
   *
   * @remarks
   */
  dailyPayCardProductEntitlement: DailyPayCardProductEntitlement;
};

/**
 * A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
 */
export type PersonAttributes = {
  /**
   * The statuses and required actions are:
   *
   * @remarks
   * - `null` The person has not been disallowed, and is free to use DailyPay.
   * - `INACTIVE` The person has not completed registration or account verification.
   * - `DELINQUENT` The person has an outstanding, unrecoverable balance with DailyPay, and should contact support.
   * - `BANNED` Access has been revoked.
   */
  disallowReason: DisallowReason | null;
  /**
   * The two-letter abbreviation for the state in which the person resides, if located in the United States.  This is used for regulatory compliance purposes.
   *
   * @remarks
   */
  stateOfResidence?: string | undefined;
  /**
   * Products that the person is enrolled in or eligible for. This data is refreshed nightly.
   *
   * @remarks
   */
  products: Products;
};

/** @internal */
export const DisallowReason$inboundSchema: z.ZodNativeEnum<
  typeof DisallowReason
> = z.nativeEnum(DisallowReason);

/** @internal */
export const DailyPayCardProductEntitlement$inboundSchema: z.ZodType<
  DailyPayCardProductEntitlement,
  z.ZodTypeDef,
  unknown
> = z.object({
  eligible: z.boolean(),
  enrolled: z.boolean(),
});

export function dailyPayCardProductEntitlementFromJSON(
  jsonString: string,
): SafeParseResult<DailyPayCardProductEntitlement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DailyPayCardProductEntitlement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DailyPayCardProductEntitlement' from JSON`,
  );
}

/** @internal */
export const Products$inboundSchema: z.ZodType<
  Products,
  z.ZodTypeDef,
  unknown
> = z.object({
  dailypay_card: z.lazy(() => DailyPayCardProductEntitlement$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "dailypay_card": "dailyPayCardProductEntitlement",
  });
});

export function productsFromJSON(
  jsonString: string,
): SafeParseResult<Products, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Products$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Products' from JSON`,
  );
}

/** @internal */
export const PersonAttributes$inboundSchema: z.ZodType<
  PersonAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  disallow_reason: z.nullable(DisallowReason$inboundSchema),
  state_of_residence: z.string().optional(),
  products: z.lazy(() => Products$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "disallow_reason": "disallowReason",
    "state_of_residence": "stateOfResidence",
  });
});

export function personAttributesFromJSON(
  jsonString: string,
): SafeParseResult<PersonAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PersonAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersonAttributes' from JSON`,
  );
}
