/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SchemeOauthClientCredentialsToken = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export type SchemeOauthClientCredentialsToken$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const SchemeOauthClientCredentialsToken$outboundSchema: z.ZodType<
  SchemeOauthClientCredentialsToken$Outbound,
  z.ZodTypeDef,
  SchemeOauthClientCredentialsToken
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://auth.dailypay.com/oauth2/token"),
});

export function schemeOauthClientCredentialsTokenToJSON(
  schemeOauthClientCredentialsToken: SchemeOauthClientCredentialsToken,
): string {
  return JSON.stringify(
    SchemeOauthClientCredentialsToken$outboundSchema.parse(
      schemeOauthClientCredentialsToken,
    ),
  );
}
