/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SchemeOauthClientCredentialsToken,
  SchemeOauthClientCredentialsToken$Outbound,
  SchemeOauthClientCredentialsToken$outboundSchema,
} from "./schemeoauthclientcredentialstoken.js";

export type Security = {
  oauthClientCredentialsToken?: SchemeOauthClientCredentialsToken | undefined;
  oauthUserToken?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  oauth_client_credentials_token?:
    | SchemeOauthClientCredentialsToken$Outbound
    | undefined;
  oauth_user_token?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  oauthClientCredentialsToken: SchemeOauthClientCredentialsToken$outboundSchema
    .optional(),
  oauthUserToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    oauthClientCredentialsToken: "oauth_client_credentials_token",
    oauthUserToken: "oauth_user_token",
  });
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
