/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TransferIdentifier = {
  type: "transfers";
  id: string;
};

/** @internal */
export const TransferIdentifier$inboundSchema: z.ZodType<
  TransferIdentifier,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("transfers"),
  id: z.string(),
});

export function transferIdentifierFromJSON(
  jsonString: string,
): SafeParseResult<TransferIdentifier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferIdentifier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferIdentifier' from JSON`,
  );
}
