/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
 *
 * @remarks
 * A preview transfer will never send.
 */
export const TransferAttributesSchedule = {
  WithinThirtyMinutes: "WITHIN_THIRTY_MINUTES",
  NextBusinessDay: "NEXT_BUSINESS_DAY",
} as const;
/**
 * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
 *
 * @remarks
 * A preview transfer will never send.
 */
export type TransferAttributesSchedule = ClosedEnum<
  typeof TransferAttributesSchedule
>;

/**
 * The status of the transfer.
 */
export const TransferAttributesStatus = {
  Pending: "PENDING",
  Settled: "SETTLED",
  Failed: "FAILED",
} as const;
/**
 * The status of the transfer.
 */
export type TransferAttributesStatus = ClosedEnum<
  typeof TransferAttributesStatus
>;

/**
 * An object representing a transfer of money from one account to another.
 *
 * @remarks
 * Created when a person takes an advance against a future paycheck, or on a daily basis
 * when we update estimated earnings based on current employment.
 */
export type TransferAttributes = {
  /**
   * Include this field to preview a transfer without sending it, to see, for example, the fee that would be charged. This will return the same response as a typical transfer request.
   *
   * @remarks
   * When the preview field is true in the response to creating a transfer, that indicates no transfer was created.
   */
  preview: boolean;
  /**
   * A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
   */
  amount: number;
  /**
   * A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
   */
  currency: string;
  /**
   * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
   *
   * @remarks
   * A preview transfer will never send.
   */
  schedule: TransferAttributesSchedule;
  /**
   * The status of the transfer.
   */
  status: TransferAttributesStatus;
  /**
   * An ISO 8601 timestamp denoting the receipt for the request.
   */
  submittedAt: Date;
  /**
   * An ISO 8601 date denoting a successful or unsuccessful resolution for the request.
   */
  resolvedAt: Date | null;
  /**
   * A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
   *
   * @remarks
   * If a transfer incurs a fee, the fee will be deducted from the amount of the transfer.
   */
  fee: number;
};

/** @internal */
export const TransferAttributesSchedule$inboundSchema: z.ZodNativeEnum<
  typeof TransferAttributesSchedule
> = z.nativeEnum(TransferAttributesSchedule);

/** @internal */
export const TransferAttributesStatus$inboundSchema: z.ZodNativeEnum<
  typeof TransferAttributesStatus
> = z.nativeEnum(TransferAttributesStatus);

/** @internal */
export const TransferAttributes$inboundSchema: z.ZodType<
  TransferAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  preview: z.boolean().default(false),
  amount: z.number().int(),
  currency: z.string(),
  schedule: TransferAttributesSchedule$inboundSchema,
  status: TransferAttributesStatus$inboundSchema,
  submitted_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  resolved_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  fee: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "submitted_at": "submittedAt",
    "resolved_at": "resolvedAt",
  });
});

export function transferAttributesFromJSON(
  jsonString: string,
): SafeParseResult<TransferAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferAttributes' from JSON`,
  );
}
