/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TransferCreateAttributes,
  TransferCreateAttributes$Outbound,
  TransferCreateAttributes$outboundSchema,
} from "./transfercreateattributes.js";
import {
  TransferCreateRelationships,
  TransferCreateRelationships$Outbound,
  TransferCreateRelationships$outboundSchema,
} from "./transfercreaterelationships.js";

export type TransferCreateResource = {
  type: "transfers";
  /**
   * The unique identifier of the transfer. Any UUID version is valid, lower-cased.
   */
  id?: string | undefined;
  /**
   * An object representing a transfer of money from one account to another.
   *
   * @remarks
   * Created when a person takes an advance against a future paycheck, or on a daily basis
   * when we update estimated earnings based on current employment.
   */
  attributes: TransferCreateAttributes;
  relationships: TransferCreateRelationships;
};

/** @internal */
export type TransferCreateResource$Outbound = {
  type: "transfers";
  id?: string | undefined;
  attributes: TransferCreateAttributes$Outbound;
  relationships: TransferCreateRelationships$Outbound;
};

/** @internal */
export const TransferCreateResource$outboundSchema: z.ZodType<
  TransferCreateResource$Outbound,
  z.ZodTypeDef,
  TransferCreateResource
> = z.object({
  type: z.literal("transfers"),
  id: z.string().optional(),
  attributes: TransferCreateAttributes$outboundSchema,
  relationships: TransferCreateRelationships$outboundSchema,
});

export function transferCreateResourceToJSON(
  transferCreateResource: TransferCreateResource,
): string {
  return JSON.stringify(
    TransferCreateResource$outboundSchema.parse(transferCreateResource),
  );
}
