/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FundingSourceResource,
  FundingSourceResource$inboundSchema,
} from "./fundingsourceresource.js";
import {
  TransferResource,
  TransferResource$inboundSchema,
} from "./transferresource.js";

/**
 * A list of transfer objects.
 */
export type TransfersData = {
  data: Array<TransferResource>;
  included?: Array<FundingSourceResource> | undefined;
};

/** @internal */
export const TransfersData$inboundSchema: z.ZodType<
  TransfersData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(TransferResource$inboundSchema),
  included: z.array(FundingSourceResource$inboundSchema).optional(),
});

export function transfersDataFromJSON(
  jsonString: string,
): SafeParseResult<TransfersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransfersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransfersData' from JSON`,
  );
}
