/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The expected time for the transfer to be completed.
 */
export const TransferDestinationCapabilitySchedule = {
  WithinThirtyMinutes: "WITHIN_THIRTY_MINUTES",
  NextBusinessDay: "NEXT_BUSINESS_DAY",
} as const;
/**
 * The expected time for the transfer to be completed.
 */
export type TransferDestinationCapabilitySchedule = ClosedEnum<
  typeof TransferDestinationCapabilitySchedule
>;

export type TransferDestinationCapability = {
  /**
   * The expected time for the transfer to be completed.
   */
  schedule: TransferDestinationCapabilitySchedule;
  /**
   * A monetary quantity expressed in units of the lowest denomination in
   *
   * @remarks
   * the associated currency. For example, `{ amount: 299, currency: 'USD'
   * }` resolves to $2.99.
   *
   * If a transfer incurs a fee, the fee will be deducted from the amount of
   * the transfer.
   */
  fee: number;
  /**
   * A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
   */
  currency: string;
};

/** @internal */
export const TransferDestinationCapabilitySchedule$inboundSchema:
  z.ZodNativeEnum<typeof TransferDestinationCapabilitySchedule> = z.nativeEnum(
    TransferDestinationCapabilitySchedule,
  );

/** @internal */
export const TransferDestinationCapability$inboundSchema: z.ZodType<
  TransferDestinationCapability,
  z.ZodTypeDef,
  unknown
> = z.object({
  schedule: TransferDestinationCapabilitySchedule$inboundSchema,
  fee: z.number().int(),
  currency: z.string(),
});

export function transferDestinationCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<TransferDestinationCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferDestinationCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferDestinationCapability' from JSON`,
  );
}
