/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
 *
 * @remarks
 * A preview transfer will never send.
 */
export const TransferCreateAttributesSchedule = {
  WithinThirtyMinutes: "WITHIN_THIRTY_MINUTES",
  NextBusinessDay: "NEXT_BUSINESS_DAY",
} as const;
/**
 * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
 *
 * @remarks
 * A preview transfer will never send.
 */
export type TransferCreateAttributesSchedule = ClosedEnum<
  typeof TransferCreateAttributesSchedule
>;

/**
 * An object representing a transfer of money from one account to another.
 *
 * @remarks
 * Created when a person takes an advance against a future paycheck, or on a daily basis
 * when we update estimated earnings based on current employment.
 */
export type TransferCreateAttributes = {
  /**
   * Include this field to preview a transfer without sending it, to see, for example, the fee that would be charged. This will return the same response as a typical transfer request.
   *
   * @remarks
   * When the preview field is true in the response to creating a transfer, that indicates no transfer was created.
   */
  preview?: boolean | undefined;
  /**
   * A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
   */
  amount: number;
  /**
   * A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
   */
  currency: string;
  /**
   * Set the schedule for the transfer. If not set, the transfer will be processed immediately.
   *
   * @remarks
   * A preview transfer will never send.
   */
  schedule: TransferCreateAttributesSchedule;
};

/** @internal */
export const TransferCreateAttributesSchedule$outboundSchema: z.ZodNativeEnum<
  typeof TransferCreateAttributesSchedule
> = z.nativeEnum(TransferCreateAttributesSchedule);

/** @internal */
export type TransferCreateAttributes$Outbound = {
  preview: boolean;
  amount: number;
  currency: string;
  schedule: string;
};

/** @internal */
export const TransferCreateAttributes$outboundSchema: z.ZodType<
  TransferCreateAttributes$Outbound,
  z.ZodTypeDef,
  TransferCreateAttributes
> = z.object({
  preview: z.boolean().default(false),
  amount: z.number().int(),
  currency: z.string(),
  schedule: TransferCreateAttributesSchedule$outboundSchema,
});

export function transferCreateAttributesToJSON(
  transferCreateAttributes: TransferCreateAttributes,
): string {
  return JSON.stringify(
    TransferCreateAttributes$outboundSchema.parse(transferCreateAttributes),
  );
}
