/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TransferCreateResource,
  TransferCreateResource$Outbound,
  TransferCreateResource$outboundSchema,
} from "./transfercreateresource.js";

export type TransferCreateData = {
  data: TransferCreateResource;
};

/** @internal */
export type TransferCreateData$Outbound = {
  data: TransferCreateResource$Outbound;
};

/** @internal */
export const TransferCreateData$outboundSchema: z.ZodType<
  TransferCreateData$Outbound,
  z.ZodTypeDef,
  TransferCreateData
> = z.object({
  data: TransferCreateResource$outboundSchema,
});

export function transferCreateDataToJSON(
  transferCreateData: TransferCreateData,
): string {
  return JSON.stringify(
    TransferCreateData$outboundSchema.parse(transferCreateData),
  );
}
