/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransferIdentifier,
  TransferIdentifier$inboundSchema,
} from "./transferidentifier.js";

export type TransferRelationship = {
  data: TransferIdentifier;
};

/** @internal */
export const TransferRelationship$inboundSchema: z.ZodType<
  TransferRelationship,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: TransferIdentifier$inboundSchema,
});

export function transferRelationshipFromJSON(
  jsonString: string,
): SafeParseResult<TransferRelationship, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferRelationship$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferRelationship' from JSON`,
  );
}
